language: go

go:
- 1.12.x

sudo: required

services:
- docker

script:
- go test ./...

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "bJDkRw55OM+OgD81Ie5EHcyObSNFlDmFW8mIB5AOqQaFsWXxcrOlDfFdbla3mTq9WrXcST2BJP02Wdc3U/mBsmLFDtoPnBqDGynwexh0tTjp9cd+HtZNsNy/KnBg9Fsp2EMOyfXuTkjbKmhzY0P95dZUNQd+R76PB1mJjmSmUV5VEI/LRfnBGp6QYSxvyMjG2scExu2T7YnyYVPHMKLAomtc5Ijbp+37OM0w7jSQwQBb2X44BR0hhveJbML2W2STb8O/GVXz9VvRbqfDFqOz3s+eAOfZPiLgae9nCaTsatBKGhkIXDms1l7c97KaA0sWeaJzebpWK3NuTsGRe1MYledbg+Rb8giRe8NR0eFVThR1kFXsLZ0wFEnA2fKC1ZrYg8ipVMkTMCOf9vZu/q91tNkYMeOlqzUp0WaowcXtu7yK6HuOXXzFedNMEVGsDJiayNvdVT4TZj4bwQpeFfHbE+/ZAHf+KoLpJ9CeVoPquCAvkdSgMJHvCJH+fg7GljZbe0OsYVJc4Oc3VQfwMqP0l1qtEqgU0GsCvi73828rnMhHAlqUiwH4veWCYp8LwJKbBsWBkp4AgNDyopzNS5heSncPSh0F+RU66EWwKmfECdmRuaexJklV/gcm78hyV8hUGko0Ok9JUY/BDOYIlw+dQGQ05hL7XgQVwXae4w6IHbU="
  - secure: "slTTNKh4rg72NUvboqgNwbRddzrs710svZ/Dz0cQe+LqE8ky9O2nzJCxlRm578FKiJnHu7AdVqh02uC4uKMj30ImZUJbUOqEuTW4r6XKb94QZI4z/V4pbUYmRZVl1tkb1lYgzga2pu9I4N64mCtuiUkaw2vQ5+Oulo0dbOIU9NrlKEuT4U/XLaWjlZqO+aZwraBFdrKsCGTeZhLjQHcnbao4T0dT3x2cJAuAmZfYDeFvgNW64W/Rx1JYoyT1a4vBkUHqBVaJnmb1O7B4H0VkHjeP6xZcDflrXu1d5txpPK4wOgJZ41W6pARDRia3VbC1z3YTQXwuHz5XKx1sE0vWRarLcSw88eHgkUJ94S7OjojNmgQQaw7OpQMcA+94KGs48QzBJ2hGy8yaQ547vZaSAx1j3ZV+yT40mFuDSWRhW5D5w9/MIpwj7klygtvvd7XMYjQDCbNcWcK/0omPrb6QCSgSG/9I0+87XwkKSAhg9fAmsz2AuRAnSfGa49/Ksnd4gAtH7k1G/XCKsvskTBvmR/ZNoTXZp0hWWZJzQ73vzo8fnJ8jgSjYP027Dm2zVCxQ6CgS7J9LGq/i2ZJ5gcYSrKqVND/SlTwHZH5RUszEdQK50wBFgZ5wS3f75YUpqtxZ+hXtKBAjQ7CUtQL/nDGDT8OhNme89BWIzMQohUxPEv4="

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=rancidfishbreath/committed
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
  
