language: go

go:
- 1.10.x

sudo: required

services:
- docker

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

script:
- dep ensure
- go test ./...
- go build

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "bJDkRw55OM+OgD81Ie5EHcyObSNFlDmFW8mIB5AOqQaFsWXxcrOlDfFdbla3mTq9WrXcST2BJP02Wdc3U/mBsmLFDtoPnBqDGynwexh0tTjp9cd+HtZNsNy/KnBg9Fsp2EMOyfXuTkjbKmhzY0P95dZUNQd+R76PB1mJjmSmUV5VEI/LRfnBGp6QYSxvyMjG2scExu2T7YnyYVPHMKLAomtc5Ijbp+37OM0w7jSQwQBb2X44BR0hhveJbML2W2STb8O/GVXz9VvRbqfDFqOz3s+eAOfZPiLgae9nCaTsatBKGhkIXDms1l7c97KaA0sWeaJzebpWK3NuTsGRe1MYledbg+Rb8giRe8NR0eFVThR1kFXsLZ0wFEnA2fKC1ZrYg8ipVMkTMCOf9vZu/q91tNkYMeOlqzUp0WaowcXtu7yK6HuOXXzFedNMEVGsDJiayNvdVT4TZj4bwQpeFfHbE+/ZAHf+KoLpJ9CeVoPquCAvkdSgMJHvCJH+fg7GljZbe0OsYVJc4Oc3VQfwMqP0l1qtEqgU0GsCvi73828rnMhHAlqUiwH4veWCYp8LwJKbBsWBkp4AgNDyopzNS5heSncPSh0F+RU66EWwKmfECdmRuaexJklV/gcm78hyV8hUGko0Ok9JUY/BDOYIlw+dQGQ05hL7XgQVwXae4w6IHbU="
  - secure: "Y3KykaaGTdRaoolzQK4HZVzXuPKqo7yM6ywQvcYf5QRHtlcFJ+HCXytdJqx8Fzqs2fMJ3I7YjaHBIWvVNKR15F07h5l7FivtnL1sPcB98EPQEex5kJl7P9zIorEvuz19EztaLEwBfB45mbAwhs8tIWE+94p2VU7u4bTV0lAHd8o2gwJfHwZP0Eu9t2MUwYabpJ466WGiO3nX4MG6/Xdo1bZ1S2jY/xHn2ROL4Vu3r8ebzbWyKDFht65TJr68bRUCD1ZmYXI69qgCw/vRbYEcsnqfD7bdzSVcNL8G1WGM64FqckgB0m32d1LjqgQMJRMOcL+NlXOWGQv65Yn6//u07UWq0RnBDBqLjeSYRSnZ14O6s9Iqfbh6SmD1FSf/f1u4TUY1KevHqjfr16MrewgxfP5DWKh48ZmVSOOKx6nJy7YOt1CyKjoeXoDr+L2s9a8ZfDBPwAczNZYwLmtc6efjM22o+Ec48K0oU4Q5cebOid+ekthFB7VV3jbOzjQbV1ZaC3l0zqQ5S7t2D3U7xBPOSIs3NgZ9EOlNhEB1WrMrCZRI9YjU6cOb1R6FZuH6pBTJkccD7Y92hIni2AslPxoybn5RWK+5uQLxSJltwXghYXgnPJjl2uqmTvJP2AwAEEKLDWS29/425ARjBEQKRnP1IdCXhODZeKfuzw0pSoruQ5U="

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=rancidfishbreath/committed
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
  
