// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: dialectpb/dialect.proto

package dialectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MySQLBinLogPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pos  uint32 `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	// snapshot_progress is populated only while the initial snapshot is
	// still running. It tracks per-table progress so a restart can
	// resume mid-snapshot instead of re-reading already-flushed rows.
	// Cleared once the snapshot completes.
	SnapshotProgress *SnapshotProgress `protobuf:"bytes,3,opt,name=snapshot_progress,json=snapshotProgress,proto3" json:"snapshot_progress,omitempty"`
}

func (x *MySQLBinLogPosition) Reset() {
	*x = MySQLBinLogPosition{}
	mi := &file_dialectpb_dialect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLBinLogPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLBinLogPosition) ProtoMessage() {}

func (x *MySQLBinLogPosition) ProtoReflect() protoreflect.Message {
	mi := &file_dialectpb_dialect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLBinLogPosition.ProtoReflect.Descriptor instead.
func (*MySQLBinLogPosition) Descriptor() ([]byte, []int) {
	return file_dialectpb_dialect_proto_rawDescGZIP(), []int{0}
}

func (x *MySQLBinLogPosition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MySQLBinLogPosition) GetPos() uint32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *MySQLBinLogPosition) GetSnapshotProgress() *SnapshotProgress {
	if x != nil {
		return x.SnapshotProgress
	}
	return nil
}

// PostgresPosition pairs the replication LSN with optional snapshot
// progress. New checkpoints always use this proto-encoded format,
// prefixed with a 0xFF magic byte so the 8-byte legacy raw-LSN format
// is still readable. See postgres.go encode/decodePosition.
type PostgresPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lsn              uint64            `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	SnapshotProgress *SnapshotProgress `protobuf:"bytes,2,opt,name=snapshot_progress,json=snapshotProgress,proto3" json:"snapshot_progress,omitempty"`
}

func (x *PostgresPosition) Reset() {
	*x = PostgresPosition{}
	mi := &file_dialectpb_dialect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresPosition) ProtoMessage() {}

func (x *PostgresPosition) ProtoReflect() protoreflect.Message {
	mi := &file_dialectpb_dialect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresPosition.ProtoReflect.Descriptor instead.
func (*PostgresPosition) Descriptor() ([]byte, []int) {
	return file_dialectpb_dialect_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresPosition) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *PostgresPosition) GetSnapshotProgress() *SnapshotProgress {
	if x != nil {
		return x.SnapshotProgress
	}
	return nil
}

// SnapshotProgress tracks where a chunked (keyset-paginated) snapshot
// has gotten to. A table is either:
//   - absent from both fields: not yet started
//   - present in last_pk_by_table: partially complete (resume WHERE pk > last_pk)
//   - present in completed_tables: done, skip entirely on resume
type SnapshotProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastPkByTable   map[string]string `protobuf:"bytes,1,rep,name=last_pk_by_table,json=lastPkByTable,proto3" json:"last_pk_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CompletedTables []string          `protobuf:"bytes,2,rep,name=completed_tables,json=completedTables,proto3" json:"completed_tables,omitempty"`
}

func (x *SnapshotProgress) Reset() {
	*x = SnapshotProgress{}
	mi := &file_dialectpb_dialect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotProgress) ProtoMessage() {}

func (x *SnapshotProgress) ProtoReflect() protoreflect.Message {
	mi := &file_dialectpb_dialect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotProgress.ProtoReflect.Descriptor instead.
func (*SnapshotProgress) Descriptor() ([]byte, []int) {
	return file_dialectpb_dialect_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotProgress) GetLastPkByTable() map[string]string {
	if x != nil {
		return x.LastPkByTable
	}
	return nil
}

func (x *SnapshotProgress) GetCompletedTables() []string {
	if x != nil {
		return x.CompletedTables
	}
	return nil
}

var File_dialectpb_dialect_proto protoreflect.FileDescriptor

var file_dialectpb_dialect_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x61, 0x6c,
	0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x65,
	0x63, 0x74, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a, 0x13, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x42, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70,
	0x6f, 0x73, 0x12, 0x48, 0x0a, 0x11, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x10, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x6e, 0x0a, 0x10,
	0x50, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c,
	0x73, 0x6e, 0x12, 0x48, 0x0a, 0x11, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x64, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x10, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0xd8, 0x01, 0x0a,
	0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x57, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x6b, 0x5f, 0x62, 0x79, 0x5f,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x69,
	0x61, 0x6c, 0x65, 0x63, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x6b, 0x42,
	0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x50, 0x6b, 0x42, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x1a, 0x40, 0x0a, 0x12, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x6b, 0x42,
	0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x68, 0x69, 0x6c, 0x62, 0x6f, 0x72, 0x6c, 0x69, 0x6e,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x64,
	0x69, 0x61, 0x6c, 0x65, 0x63, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dialectpb_dialect_proto_rawDescOnce sync.Once
	file_dialectpb_dialect_proto_rawDescData = file_dialectpb_dialect_proto_rawDesc
)

func file_dialectpb_dialect_proto_rawDescGZIP() []byte {
	file_dialectpb_dialect_proto_rawDescOnce.Do(func() {
		file_dialectpb_dialect_proto_rawDescData = protoimpl.X.CompressGZIP(file_dialectpb_dialect_proto_rawDescData)
	})
	return file_dialectpb_dialect_proto_rawDescData
}

var file_dialectpb_dialect_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dialectpb_dialect_proto_goTypes = []any{
	(*MySQLBinLogPosition)(nil), // 0: dialectpb.MySQLBinLogPosition
	(*PostgresPosition)(nil),    // 1: dialectpb.PostgresPosition
	(*SnapshotProgress)(nil),    // 2: dialectpb.SnapshotProgress
	nil,                         // 3: dialectpb.SnapshotProgress.LastPkByTableEntry
}
var file_dialectpb_dialect_proto_depIdxs = []int32{
	2, // 0: dialectpb.MySQLBinLogPosition.snapshot_progress:type_name -> dialectpb.SnapshotProgress
	2, // 1: dialectpb.PostgresPosition.snapshot_progress:type_name -> dialectpb.SnapshotProgress
	3, // 2: dialectpb.SnapshotProgress.last_pk_by_table:type_name -> dialectpb.SnapshotProgress.LastPkByTableEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dialectpb_dialect_proto_init() }
func file_dialectpb_dialect_proto_init() {
	if File_dialectpb_dialect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dialectpb_dialect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dialectpb_dialect_proto_goTypes,
		DependencyIndexes: file_dialectpb_dialect_proto_depIdxs,
		MessageInfos:      file_dialectpb_dialect_proto_msgTypes,
	}.Build()
	File_dialectpb_dialect_proto = out.File
	file_dialectpb_dialect_proto_rawDesc = nil
	file_dialectpb_dialect_proto_goTypes = nil
	file_dialectpb_dialect_proto_depIdxs = nil
}
