// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: clusterpb/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogValidationStrategy int32

const (
	LogValidationStrategy_NoValidation   LogValidationStrategy = 0
	LogValidationStrategy_ValidateSchema LogValidationStrategy = 1
)

// Enum value maps for LogValidationStrategy.
var (
	LogValidationStrategy_name = map[int32]string{
		0: "NoValidation",
		1: "ValidateSchema",
	}
	LogValidationStrategy_value = map[string]int32{
		"NoValidation":   0,
		"ValidateSchema": 1,
	}
)

func (x LogValidationStrategy) Enum() *LogValidationStrategy {
	p := new(LogValidationStrategy)
	*p = x
	return p
}

func (x LogValidationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogValidationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_clusterpb_cluster_proto_enumTypes[0].Descriptor()
}

func (LogValidationStrategy) Type() protoreflect.EnumType {
	return &file_clusterpb_cluster_proto_enumTypes[0]
}

func (x LogValidationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogValidationStrategy.Descriptor instead.
func (LogValidationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{0}
}

// LogEntityKind declares what the entities written under a type are —
// how much interpretation a consumer needs to apply one.
// EntityKindUnspecified is the grandfathered default: every type
// written before the field existed unmarshals as it, and it behaves
// exactly like an untyped topic (no enforcement ever applies). The
// entity kind is immutable once declared (ProposeType rejects changes
// across version bumps), so the value at any version is the value
// forever.
type LogEntityKind int32

const (
	LogEntityKind_EntityKindUnspecified LogEntityKind = 0
	// Full objects; apply = overwrite (LWW per key).
	LogEntityKind_EntityKindSnapshot LogEntityKind = 1
	// State-relative patches; hostile to at-least-once sync delivery,
	// rejected at type creation. Reserved so the taxonomy is complete.
	LogEntityKind_EntityKindDelta LogEntityKind = 2
	// Domain facts; apply = fold via domain rules.
	LogEntityKind_EntityKindEvent LogEntityKind = 3
	// Requests; replay is dangerous, lifecycle belongs to the consumer.
	LogEntityKind_EntityKindCommand LogEntityKind = 4
	// Facts with no aggregate to converge on (audit, telemetry); apply =
	// append, never folded.
	LogEntityKind_EntityKindStandalone LogEntityKind = 5
	// Full states in a retained, ordered series — like Snapshot, but every
	// prior version is kept and individually addressable (roll back / read
	// "as of"). The latest is current; the history is part of the data, so
	// it is never compacted away.
	LogEntityKind_EntityKindRevision LogEntityKind = 6
)

// Enum value maps for LogEntityKind.
var (
	LogEntityKind_name = map[int32]string{
		0: "EntityKindUnspecified",
		1: "EntityKindSnapshot",
		2: "EntityKindDelta",
		3: "EntityKindEvent",
		4: "EntityKindCommand",
		5: "EntityKindStandalone",
		6: "EntityKindRevision",
	}
	LogEntityKind_value = map[string]int32{
		"EntityKindUnspecified": 0,
		"EntityKindSnapshot":    1,
		"EntityKindDelta":       2,
		"EntityKindEvent":       3,
		"EntityKindCommand":     4,
		"EntityKindStandalone":  5,
		"EntityKindRevision":    6,
	}
)

func (x LogEntityKind) Enum() *LogEntityKind {
	p := new(LogEntityKind)
	*p = x
	return p
}

func (x LogEntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_clusterpb_cluster_proto_enumTypes[1].Descriptor()
}

func (LogEntityKind) Type() protoreflect.EnumType {
	return &file_clusterpb_cluster_proto_enumTypes[1]
}

func (x LogEntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntityKind.Descriptor instead.
func (LogEntityKind) EnumDescriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{1}
}

// TypeRef identifies a Type by the compound (ID, Version) key. It is
// the pointer a LogEntity carries so future readers can resolve the
// entity's Type at the exact version that was current at propose time.
// A Version of 0 means "unset" — the resolver treats that as "resolve
// as latest," which matches the pre-versioning behavior for log entries
// written before TypeRef existed.
type TypeRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *TypeRef) Reset() {
	*x = TypeRef{}
	mi := &file_clusterpb_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRef) ProtoMessage() {}

func (x *TypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRef.ProtoReflect.Descriptor instead.
func (*TypeRef) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *TypeRef) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TypeRef) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LogEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *TypeRef `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key  []byte   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Data []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	// generation is the ingest refresh epoch that stamped this entity — a
	// per-ingestable monotonic counter (starting at 1) the worker carries in
	// its position and applies to EVERY emitted entity, snapshot and streaming
	// alike. It drives reconciling ("full-refresh") snapshots: on a full
	// re-snapshot the worker bumps the epoch, re-emits every live source row at
	// the new epoch, and closes with a refresh-boundary marker; a keyed sink
	// then sweeps any row still carrying an older generation (a row deleted at
	// the source in a lost change-data window, which a positive re-enumeration
	// can never signal). 0 means "not stamped by a refresh-managed ingest"
	// (direct user writes, config records, pre-feature log entries) and is
	// never swept. Backward compatible: old entries unmarshal as 0.
	Generation uint64 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	// refresh_boundary marks this entity as a refresh-boundary MARKER rather
	// than row data: it carries no Key/Data, and `generation` is the epoch G at
	// which its topic was fully refreshed. A keyed sink reacts by sweeping every
	// row of that topic whose generation is < G (>= 1). Emitted once per topic
	// at the end of an all-tables full refresh — NEVER after a partial
	// added-table backfill (that would delete the topic's sibling tables). A
	// consumer that does not implement reconciliation treats it as a no-op.
	RefreshBoundary bool `protobuf:"varint,6,opt,name=refresh_boundary,json=refreshBoundary,proto3" json:"refresh_boundary,omitempty"`
	// body is the typed control envelope: exactly one variant per entity, so an
	// entity's role — row datum, delete tombstone, refresh marker — is explicit
	// on the wire, and impossible states (a refresh carrying a key, a row
	// carrying keep_data) are unrepresentable. Writers encode EVERY entity as a
	// body variant; the flat Key/Data/generation/refresh_boundary fields above
	// are LEGACY (logs written by <= 0.7.2-beta), mapped into the same view at
	// decode and never written again. Do not add new flat fields — add a new
	// body variant instead: wire-level add-only (an old reader sees body unset),
	// with its EMISSION feature-gated (db.featureEnabled) so the variant is only
	// committed once every member can apply it. See docs/api-compatibility.md.
	//
	// Types that are assignable to Body:
	//
	//	*LogEntity_Row
	//	*LogEntity_Delete
	//	*LogEntity_Refresh
	Body isLogEntity_Body `protobuf_oneof:"body"`
}

func (x *LogEntity) Reset() {
	*x = LogEntity{}
	mi := &file_clusterpb_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntity) ProtoMessage() {}

func (x *LogEntity) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntity.ProtoReflect.Descriptor instead.
func (*LogEntity) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntity) GetType() *TypeRef {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *LogEntity) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LogEntity) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEntity) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *LogEntity) GetRefreshBoundary() bool {
	if x != nil {
		return x.RefreshBoundary
	}
	return false
}

func (m *LogEntity) GetBody() isLogEntity_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *LogEntity) GetRow() *LogRow {
	if x, ok := x.GetBody().(*LogEntity_Row); ok {
		return x.Row
	}
	return nil
}

func (x *LogEntity) GetDelete() *LogDelete {
	if x, ok := x.GetBody().(*LogEntity_Delete); ok {
		return x.Delete
	}
	return nil
}

func (x *LogEntity) GetRefresh() *LogRefresh {
	if x, ok := x.GetBody().(*LogEntity_Refresh); ok {
		return x.Refresh
	}
	return nil
}

type isLogEntity_Body interface {
	isLogEntity_Body()
}

type LogEntity_Row struct {
	Row *LogRow `protobuf:"bytes,7,opt,name=row,proto3,oneof"`
}

type LogEntity_Delete struct {
	Delete *LogDelete `protobuf:"bytes,8,opt,name=delete,proto3,oneof"`
}

type LogEntity_Refresh struct {
	Refresh *LogRefresh `protobuf:"bytes,9,opt,name=refresh,proto3,oneof"`
}

func (*LogEntity_Row) isLogEntity_Body() {}

func (*LogEntity_Delete) isLogEntity_Body() {}

func (*LogEntity_Refresh) isLogEntity_Body() {}

// LogRow is an upsert: a keyed datum on a topic (or an internal config write).
type LogRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// generation is the ingest reconciling-refresh epoch stamped on the row;
	// 0 = not stamped by a refresh-managed ingest.
	Generation uint64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
}

func (x *LogRow) Reset() {
	*x = LogRow{}
	mi := &file_clusterpb_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRow) ProtoMessage() {}

func (x *LogRow) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRow.ProtoReflect.Descriptor instead.
func (*LogRow) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *LogRow) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LogRow) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogRow) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// LogDelete is a keyed tombstone: remove the record keyed by key downstream.
type LogDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// generation mirrors LogRow's — CDC delete tombstones are epoch-stamped too.
	Generation uint64 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	// keep_data marks a syncable-config delete whose operator asked to PRESERVE
	// the destination data (DELETE ?keepData=true): the owner node skips the
	// destination teardown on apply. Entity-borne so every node applies the same
	// intent deterministically — a node-local intent map was lost on a
	// propose→apply leadership change and wrongly cleared on ambiguous propose
	// failures.
	KeepData bool `protobuf:"varint,3,opt,name=keep_data,json=keepData,proto3" json:"keep_data,omitempty"`
}

func (x *LogDelete) Reset() {
	*x = LogDelete{}
	mi := &file_clusterpb_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogDelete) ProtoMessage() {}

func (x *LogDelete) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogDelete.ProtoReflect.Descriptor instead.
func (*LogDelete) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *LogDelete) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LogDelete) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *LogDelete) GetKeepData() bool {
	if x != nil {
		return x.KeepData
	}
	return false
}

// LogRefresh is the reconciling-refresh boundary marker: the topic was fully
// refreshed at epoch generation; keyed sinks sweep rows below it.
type LogRefresh struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
}

func (x *LogRefresh) Reset() {
	*x = LogRefresh{}
	mi := &file_clusterpb_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRefresh) ProtoMessage() {}

func (x *LogRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRefresh.ProtoReflect.Descriptor instead.
func (*LogRefresh) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *LogRefresh) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type LogProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogEntities []*LogEntity `protobuf:"bytes,1,rep,name=logEntities,proto3" json:"logEntities,omitempty"`
	// requestID lets db.Propose's caller wait for *its* proposal to be
	// applied. db.DB holds a request-ID-keyed waiter map; the apply path
	// signals the waiter after the entry's bucket writes succeed. A
	// requestID of 0 means "no waiter" — used by system-internal proposers
	// (ingest worker, sync worker) that don't need read-after-write
	// semantics. Backward-compatible: old log entries unmarshal as 0.
	RequestID uint64 `protobuf:"varint,2,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// ingestableID + sourceSeq tag a proposal emitted by an ingest worker
	// for a given source event. sourceSeq is a per-ingestable monotonic
	// position (Postgres LSN, MySQL binlog file+offset) the dialect stamps
	// on every emitted proposal. The apply path advances a per-ingestable
	// highwater to max(highwater, sourceSeq), and the leader's worker
	// skips re-emitted proposals (sourceSeq <= highwater) BEFORE they
	// enter raft — giving effectively-once ingest. Empty ID / zero seq
	// means "not an ingest proposal" and is never deduped. Backward
	// compatible: pre-feature entries unmarshal as "" / 0.
	IngestableID string `protobuf:"bytes,3,opt,name=ingestableID,proto3" json:"ingestableID,omitempty"`
	SourceSeq    uint64 `protobuf:"varint,4,opt,name=sourceSeq,proto3" json:"sourceSeq,omitempty"`
	// position, when set, is the ingest resume checkpoint this proposal
	// establishes, applied ATOMICALLY with the proposal's entities in one raft
	// entry (the apply path calls the same guarded put as a standalone position
	// entity, keyed by ingestableID). Snapshot batches carry it so a crash can
	// never land between a committed batch and its checkpoint — the case
	// SourceSeq dedup cannot cover (snapshot rows have sourceSeq 0). Streaming
	// still checkpoints out-of-band. Empty means "no bundled position".
	Position []byte `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *LogProposal) Reset() {
	*x = LogProposal{}
	mi := &file_clusterpb_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogProposal) ProtoMessage() {}

func (x *LogProposal) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogProposal.ProtoReflect.Descriptor instead.
func (*LogProposal) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *LogProposal) GetLogEntities() []*LogEntity {
	if x != nil {
		return x.LogEntities
	}
	return nil
}

func (x *LogProposal) GetRequestID() uint64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *LogProposal) GetIngestableID() string {
	if x != nil {
		return x.IngestableID
	}
	return ""
}

func (x *LogProposal) GetSourceSeq() uint64 {
	if x != nil {
		return x.SourceSeq
	}
	return 0
}

func (x *LogProposal) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

type LogType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string                `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Version    int32                 `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	SchemaType string                `protobuf:"bytes,4,opt,name=SchemaType,proto3" json:"SchemaType,omitempty"`
	Schema     []byte                `protobuf:"bytes,5,opt,name=Schema,proto3" json:"Schema,omitempty"`
	Validate   LogValidationStrategy `protobuf:"varint,6,opt,name=Validate,proto3,enum=clusterpb.LogValidationStrategy" json:"Validate,omitempty"`
	// Migration is the transform program that upgrades data written
	// against version-1 of this type into the shape this version
	// expects. Interpreted as a jq program against the entity's JSON
	// payload. Empty when this is the first version (Version 1) or when
	// the schema bump is additive enough that no transform is needed.
	// Applied only when a syncable is configured in "always-current"
	// mode; "as-stored" syncables see the raw entity data and handle
	// versioning themselves.
	Migration []byte `protobuf:"bytes,7,opt,name=Migration,proto3" json:"Migration,omitempty"`
	// EntityKind classifies what the entities written under this type
	// are (see LogEntityKind). Additive: log entries embed only
	// TypeRef, so this touches type metadata only — pre-existing types
	// unmarshal as EntityKindUnspecified and behave exactly as before.
	EntityKind LogEntityKind `protobuf:"varint,8,opt,name=EntityKind,proto3,enum=clusterpb.LogEntityKind" json:"EntityKind,omitempty"`
	// Discriminator is a jsonpath (e.g. "$.event_type") naming the
	// field that distinguishes entity variants. Only meaningful for
	// EntityKindEvent; recorded so projection-style syncables can
	// default their match rules to it.
	Discriminator string `protobuf:"bytes,9,opt,name=Discriminator,proto3" json:"Discriminator,omitempty"`
}

func (x *LogType) Reset() {
	*x = LogType{}
	mi := &file_clusterpb_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogType) ProtoMessage() {}

func (x *LogType) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogType.ProtoReflect.Descriptor instead.
func (*LogType) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *LogType) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogType) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LogType) GetSchemaType() string {
	if x != nil {
		return x.SchemaType
	}
	return ""
}

func (x *LogType) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *LogType) GetValidate() LogValidationStrategy {
	if x != nil {
		return x.Validate
	}
	return LogValidationStrategy_NoValidation
}

func (x *LogType) GetMigration() []byte {
	if x != nil {
		return x.Migration
	}
	return nil
}

func (x *LogType) GetEntityKind() LogEntityKind {
	if x != nil {
		return x.EntityKind
	}
	return LogEntityKind_EntityKindUnspecified
}

func (x *LogType) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

type LogConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *LogConfiguration) Reset() {
	*x = LogConfiguration{}
	mi := &file_clusterpb_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfiguration) ProtoMessage() {}

func (x *LogConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfiguration.ProtoReflect.Descriptor instead.
func (*LogConfiguration) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *LogConfiguration) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogConfiguration) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *LogConfiguration) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogSyncableIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *LogSyncableIndex) Reset() {
	*x = LogSyncableIndex{}
	mi := &file_clusterpb_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSyncableIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSyncableIndex) ProtoMessage() {}

func (x *LogSyncableIndex) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSyncableIndex.ProtoReflect.Descriptor instead.
func (*LogSyncableIndex) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *LogSyncableIndex) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogSyncableIndex) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type LogIngestablePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position []byte `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
}

func (x *LogIngestablePosition) Reset() {
	*x = LogIngestablePosition{}
	mi := &file_clusterpb_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogIngestablePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogIngestablePosition) ProtoMessage() {}

func (x *LogIngestablePosition) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogIngestablePosition.ProtoReflect.Descriptor instead.
func (*LogIngestablePosition) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *LogIngestablePosition) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogIngestablePosition) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

type LogSyncableDeadLetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID is the syncable that gave up on and skipped a proposal.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// index is the raft index of the failed proposal in the permanent
	// event log — the pointer back to the dropped data (the proposal
	// itself stays in the log; we only record that it was skipped).
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// timestampUnixNano is the wall-clock time the leader recorded the
	// failure. Stamped once at propose time so apply is content-
	// deterministic on every replica (every node stores the same bytes).
	TimestampUnixNano int64 `protobuf:"varint,3,opt,name=timestampUnixNano,proto3" json:"timestampUnixNano,omitempty"`
	// kind classifies the skip: "permanent" (Sync returned a non-retryable
	// error) or "manual" (an operator skipped a syncable wedged on a
	// transient error via DeadLetterStuckSyncable).
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// message is the (truncated) error string from the failing Sync.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogSyncableDeadLetter) Reset() {
	*x = LogSyncableDeadLetter{}
	mi := &file_clusterpb_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSyncableDeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSyncableDeadLetter) ProtoMessage() {}

func (x *LogSyncableDeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSyncableDeadLetter.ProtoReflect.Descriptor instead.
func (*LogSyncableDeadLetter) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *LogSyncableDeadLetter) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogSyncableDeadLetter) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogSyncableDeadLetter) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogSyncableDeadLetter) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LogSyncableDeadLetter) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LogSyncableStuck is published by a syncable's worker when it has been
// blocked retrying a transient error for longer than a debounce window. It
// is replicated like every other metadata entry so any node can report
// "syncable X is blocked on index N" (GET /syncable/{id}/status) and so an
// operator's dead-letter request can be served from any node. It is
// upsert/delete keyed by syncable id (one current value per syncable);
// deleted when the worker makes progress.
type LogSyncableStuck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID is the blocked syncable.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// index is the raft index of the proposal (or, for a batch syncable, the
	// head of the batch) the worker is currently blocked on.
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// sinceUnixNano is when the worker first wedged on this proposal.
	SinceUnixNano int64 `protobuf:"varint,3,opt,name=sinceUnixNano,proto3" json:"sinceUnixNano,omitempty"`
	// message is the (truncated) last transient error.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// parked is true when the syncable's worker has TERMINALLY parked — the sync
	// circuit breaker tripped on a systematic config fault — rather than being
	// transiently stuck retrying. A parked record survives the worker's exit and
	// clears only on an operator fix (a new config version) or a delete. Default
	// false = transiently stuck, so records written before this field (and records
	// read by an older binary that ignores it) read as transiently stuck.
	Parked bool `protobuf:"varint,5,opt,name=parked,proto3" json:"parked,omitempty"`
}

func (x *LogSyncableStuck) Reset() {
	*x = LogSyncableStuck{}
	mi := &file_clusterpb_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSyncableStuck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSyncableStuck) ProtoMessage() {}

func (x *LogSyncableStuck) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSyncableStuck.ProtoReflect.Descriptor instead.
func (*LogSyncableStuck) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *LogSyncableStuck) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogSyncableStuck) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogSyncableStuck) GetSinceUnixNano() int64 {
	if x != nil {
		return x.SinceUnixNano
	}
	return 0
}

func (x *LogSyncableStuck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogSyncableStuck) GetParked() bool {
	if x != nil {
		return x.Parked
	}
	return false
}

// LogIngestableStuck records that an ingestable's worker has TERMINALLY parked —
// the freeze/restart supervisor gave up after repeated freezes at the same resume
// position (a proposal it cannot commit, most often a row or transaction over the
// proposal-size cap). Keyed by ingestable id; replicated so any node reports it.
// Like the syncable parked record it survives the worker's exit and clears only on
// an operator fix (a new config version) or a delete.
type LogIngestableStuck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID is the parked ingestable.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// sinceUnixNano is when the supervisor gave up.
	SinceUnixNano int64 `protobuf:"varint,2,opt,name=sinceUnixNano,proto3" json:"sinceUnixNano,omitempty"`
	// message is the (truncated, redacted) give-up cause.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogIngestableStuck) Reset() {
	*x = LogIngestableStuck{}
	mi := &file_clusterpb_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogIngestableStuck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogIngestableStuck) ProtoMessage() {}

func (x *LogIngestableStuck) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogIngestableStuck.ProtoReflect.Descriptor instead.
func (*LogIngestableStuck) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *LogIngestableStuck) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogIngestableStuck) GetSinceUnixNano() int64 {
	if x != nil {
		return x.SinceUnixNano
	}
	return 0
}

func (x *LogIngestableStuck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LogSyncableSkipRequest is proposed by the dead-letter endpoint (from any
// node) to ask the syncable's worker to skip what it is currently blocked
// on. It carries the index from the matching LogSyncableStuck so the worker
// can only ever skip the exact proposal the operator saw — never a different
// one the worker may have moved on to. Upsert/delete keyed by syncable id;
// the worker deletes it once honored (or drops it as stale).
type LogSyncableSkipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID is the syncable to unstick.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// index is the blocked index the operator requested be skipped; the
	// worker honors the request only while its current stuck index matches.
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *LogSyncableSkipRequest) Reset() {
	*x = LogSyncableSkipRequest{}
	mi := &file_clusterpb_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSyncableSkipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSyncableSkipRequest) ProtoMessage() {}

func (x *LogSyncableSkipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSyncableSkipRequest.ProtoReflect.Descriptor instead.
func (*LogSyncableSkipRequest) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *LogSyncableSkipRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogSyncableSkipRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// LogTypeMigrationDeadLetter records that a type-migration program (jq)
// failed at runtime on the proposal at index. It is the type-keyed twin of
// LogSyncableDeadLetter: the syncable record says "syncable S skipped index
// I", this one says "type T's vN migration is what broke it" — so an
// operator can enumerate which proposals failed migration for a type and
// retry them after fixing the program. Proposed by the sync worker alongside
// the syncable dead letter; applied deterministically on every node.
type LogTypeMigrationDeadLetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// typeID is the type whose migration program failed.
	TypeID string `protobuf:"bytes,1,opt,name=typeID,proto3" json:"typeID,omitempty"`
	// index is the raft index of the proposal whose entity failed to
	// migrate (the data itself stays in the permanent event log).
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// timestampUnixNano is stamped once at propose time so apply is
	// content-deterministic on every replica.
	TimestampUnixNano int64 `protobuf:"varint,3,opt,name=timestampUnixNano,proto3" json:"timestampUnixNano,omitempty"`
	// fromVersion -> toVersion identify the failing chain step: the
	// toVersion migration program is the one that errored.
	FromVersion int32 `protobuf:"varint,4,opt,name=fromVersion,proto3" json:"fromVersion,omitempty"`
	ToVersion   int32 `protobuf:"varint,5,opt,name=toVersion,proto3" json:"toVersion,omitempty"`
	// message is the (truncated) error string from the failing program.
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogTypeMigrationDeadLetter) Reset() {
	*x = LogTypeMigrationDeadLetter{}
	mi := &file_clusterpb_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTypeMigrationDeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTypeMigrationDeadLetter) ProtoMessage() {}

func (x *LogTypeMigrationDeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTypeMigrationDeadLetter.ProtoReflect.Descriptor instead.
func (*LogTypeMigrationDeadLetter) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *LogTypeMigrationDeadLetter) GetTypeID() string {
	if x != nil {
		return x.TypeID
	}
	return ""
}

func (x *LogTypeMigrationDeadLetter) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogTypeMigrationDeadLetter) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogTypeMigrationDeadLetter) GetFromVersion() int32 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *LogTypeMigrationDeadLetter) GetToVersion() int32 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

func (x *LogTypeMigrationDeadLetter) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LogScrub is the payload of a Scrub command — the committed instruction
// that triggers physical removal of already-delete-proposed entities from
// the permanent event log. It carries one value, the upper-bound raft
// index B (the "freeze line"): only event-log entries at raft index <= B
// are eligible for removal, and only entities whose (type,key) was
// delete-proposed at a raft index <= B. Pinning B inside the committed
// command makes every replica remove the identical set, so the rewritten
// event logs stay byte-identical across nodes (the rsync-rebuild and
// determinism-test contract). See docs/event-log-architecture.md
// § "Right-to-be-forgotten / deletes".
type LogScrub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpperBound uint64 `protobuf:"varint,1,opt,name=upperBound,proto3" json:"upperBound,omitempty"`
}

func (x *LogScrub) Reset() {
	*x = LogScrub{}
	mi := &file_clusterpb_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogScrub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogScrub) ProtoMessage() {}

func (x *LogScrub) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogScrub.ProtoReflect.Descriptor instead.
func (*LogScrub) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *LogScrub) GetUpperBound() uint64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

// LogNodeAPIURL is a node's self-announcement of its advertised HTTP API
// base URL (COMMITTED_API_URL), replicated so every node can discover the
// address to reach any other — in particular the leader, for proxying
// leader-only reads (GET /v1/membership) from a follower. Raft replicates
// only node ids and raft peer URLs, never API addresses, so each node
// announces its own once it joins. Upsert keyed by node id; the apply path
// stores it in the memberAPIURLs bucket. See raft-leader-read-proxy.md.
type LogNodeAPIURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	ApiURL string `protobuf:"bytes,2,opt,name=apiURL,proto3" json:"apiURL,omitempty"`
}

func (x *LogNodeAPIURL) Reset() {
	*x = LogNodeAPIURL{}
	mi := &file_clusterpb_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogNodeAPIURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogNodeAPIURL) ProtoMessage() {}

func (x *LogNodeAPIURL) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogNodeAPIURL.ProtoReflect.Descriptor instead.
func (*LogNodeAPIURL) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *LogNodeAPIURL) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *LogNodeAPIURL) GetApiURL() string {
	if x != nil {
		return x.ApiURL
	}
	return ""
}

// LogNodeVersion is a node's self-announcement of the highest cluster feature
// level its binary supports (version.FeatureLevel). Replicated so any node can
// compute the cluster-agreed minimum and gate emission of a feature's entries
// until every member can apply them — the fix for semantic version skew (a new
// system type must not reach an old node, a refresh-boundary marker must not
// reach a node that can't interpret it). Upsert keyed by node id; the apply
// path stores it in the memberVersions bucket. See node_version.go and
// docs/api-compatibility.md.
type LogNodeVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID       uint64 `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	FeatureLevel uint64 `protobuf:"varint,2,opt,name=featureLevel,proto3" json:"featureLevel,omitempty"`
}

func (x *LogNodeVersion) Reset() {
	*x = LogNodeVersion{}
	mi := &file_clusterpb_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogNodeVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogNodeVersion) ProtoMessage() {}

func (x *LogNodeVersion) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogNodeVersion.ProtoReflect.Descriptor instead.
func (*LogNodeVersion) Descriptor() ([]byte, []int) {
	return file_clusterpb_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *LogNodeVersion) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *LogNodeVersion) GetFeatureLevel() uint64 {
	if x != nil {
		return x.FeatureLevel
	}
	return 0
}

var File_clusterpb_cluster_proto protoreflect.FileDescriptor

var file_clusterpb_cluster_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x70, 0x62, 0x22, 0x33, 0x0a, 0x07, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xc7, 0x02, 0x0a, 0x09, 0x4c, 0x6f,
	0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x66, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79,
	0x12, 0x25, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x6f, 0x77,
	0x48, 0x00, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x2e, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x48,
	0x00, 0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x4e, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x2c, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x1e, 0x0a,
	0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc1, 0x01,
	0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x36, 0x0a,
	0x0b, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c,
	0x6f, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xbb, 0x02, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x12, 0x3c, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0a, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x69, 0x73,
	0x63, 0x72, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x44, 0x69, 0x73, 0x63, 0x72, 0x69, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x66, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x53, 0x79,
	0x6e, 0x63, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x43, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x53, 0x79,
	0x6e, 0x63, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x61, 0x64, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78,
	0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x53, 0x79, 0x6e, 0x63, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x74, 0x75, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e,
	0x61, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x6b, 0x65, 0x64, 0x22, 0x64, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x75, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x69, 0x6e, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x16, 0x4c,
	0x6f, 0x67, 0x53, 0x79, 0x6e, 0x63, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x6b, 0x69, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xd2, 0x01, 0x0a, 0x1a,
	0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x61, 0x64, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x79,
	0x70, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e,
	0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66, 0x72, 0x6f,
	0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x53, 0x63, 0x72, 0x75, 0x62, 0x12, 0x1e, 0x0a, 0x0a,
	0x75, 0x70, 0x70, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x75, 0x70, 0x70, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x3f, 0x0a, 0x0d,
	0x4c, 0x6f, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x50, 0x49, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x55, 0x52, 0x4c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x55, 0x52, 0x4c, 0x22, 0x4c, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2a, 0x3d, 0x0a, 0x15, 0x4c,
	0x6f, 0x67, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x10, 0x01, 0x2a, 0xb5, 0x01, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x15,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69,
	0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10, 0x04,
	0x12, 0x18, 0x0a, 0x14, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x6c, 0x6f, 0x6e, 0x65, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x10, 0x06, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x64, 0x62, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clusterpb_cluster_proto_rawDescOnce sync.Once
	file_clusterpb_cluster_proto_rawDescData = file_clusterpb_cluster_proto_rawDesc
)

func file_clusterpb_cluster_proto_rawDescGZIP() []byte {
	file_clusterpb_cluster_proto_rawDescOnce.Do(func() {
		file_clusterpb_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_clusterpb_cluster_proto_rawDescData)
	})
	return file_clusterpb_cluster_proto_rawDescData
}

var file_clusterpb_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_clusterpb_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_clusterpb_cluster_proto_goTypes = []any{
	(LogValidationStrategy)(0),         // 0: clusterpb.LogValidationStrategy
	(LogEntityKind)(0),                 // 1: clusterpb.LogEntityKind
	(*TypeRef)(nil),                    // 2: clusterpb.TypeRef
	(*LogEntity)(nil),                  // 3: clusterpb.LogEntity
	(*LogRow)(nil),                     // 4: clusterpb.LogRow
	(*LogDelete)(nil),                  // 5: clusterpb.LogDelete
	(*LogRefresh)(nil),                 // 6: clusterpb.LogRefresh
	(*LogProposal)(nil),                // 7: clusterpb.LogProposal
	(*LogType)(nil),                    // 8: clusterpb.LogType
	(*LogConfiguration)(nil),           // 9: clusterpb.LogConfiguration
	(*LogSyncableIndex)(nil),           // 10: clusterpb.LogSyncableIndex
	(*LogIngestablePosition)(nil),      // 11: clusterpb.LogIngestablePosition
	(*LogSyncableDeadLetter)(nil),      // 12: clusterpb.LogSyncableDeadLetter
	(*LogSyncableStuck)(nil),           // 13: clusterpb.LogSyncableStuck
	(*LogIngestableStuck)(nil),         // 14: clusterpb.LogIngestableStuck
	(*LogSyncableSkipRequest)(nil),     // 15: clusterpb.LogSyncableSkipRequest
	(*LogTypeMigrationDeadLetter)(nil), // 16: clusterpb.LogTypeMigrationDeadLetter
	(*LogScrub)(nil),                   // 17: clusterpb.LogScrub
	(*LogNodeAPIURL)(nil),              // 18: clusterpb.LogNodeAPIURL
	(*LogNodeVersion)(nil),             // 19: clusterpb.LogNodeVersion
}
var file_clusterpb_cluster_proto_depIdxs = []int32{
	2, // 0: clusterpb.LogEntity.type:type_name -> clusterpb.TypeRef
	4, // 1: clusterpb.LogEntity.row:type_name -> clusterpb.LogRow
	5, // 2: clusterpb.LogEntity.delete:type_name -> clusterpb.LogDelete
	6, // 3: clusterpb.LogEntity.refresh:type_name -> clusterpb.LogRefresh
	3, // 4: clusterpb.LogProposal.logEntities:type_name -> clusterpb.LogEntity
	0, // 5: clusterpb.LogType.Validate:type_name -> clusterpb.LogValidationStrategy
	1, // 6: clusterpb.LogType.EntityKind:type_name -> clusterpb.LogEntityKind
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_clusterpb_cluster_proto_init() }
func file_clusterpb_cluster_proto_init() {
	if File_clusterpb_cluster_proto != nil {
		return
	}
	file_clusterpb_cluster_proto_msgTypes[1].OneofWrappers = []any{
		(*LogEntity_Row)(nil),
		(*LogEntity_Delete)(nil),
		(*LogEntity_Refresh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clusterpb_cluster_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clusterpb_cluster_proto_goTypes,
		DependencyIndexes: file_clusterpb_cluster_proto_depIdxs,
		EnumInfos:         file_clusterpb_cluster_proto_enumTypes,
		MessageInfos:      file_clusterpb_cluster_proto_msgTypes,
	}.Build()
	File_clusterpb_cluster_proto = out.File
	file_clusterpb_cluster_proto_rawDesc = nil
	file_clusterpb_cluster_proto_goTypes = nil
	file_clusterpb_cluster_proto_depIdxs = nil
}
