services:
 db:
   image: mysql:latest
   container_name: pinkFlamingosContainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=test
   volumes:
     - /Users/phil/repositories/committeddb/committed/docker/db:/var/lib/mysql 