[ingestable]
name = "person-ingest"
type = "sql"

[sql]
dialect = "postgres"
topic = "person"
connectionString = "postgres://test:${CATALOG_DB_PASSWORD}@db:5432/catalog?sslmode=disable"
primaryKey = "person_id"
tables = ["ingress.person"]
mapAllColumns = true

[sql.postgres]
slot_name = "committed_person_slot"
publication = "committed_person_pub"
