# Determines what the rest of the config will look like
[db]
type = "sql"

[sql]
# driver = "ql"
# connectionString = "memory://foo"
db = "testdb"

[sql.topic]
name = "test1"

[[sql.topic.mapping]]
jsonPath = "$.Key"
table = "foo"
column = "key"

[[sql.topic.mapping]]
jsonPath = "$.One"
table = "foo"
column = "two"