// Code generated by counterfeiter. DO NOT EDIT.
package clusterfakes

import (
	"context"
	"sync"
	"time"

	"github.com/philborlin/committed/internal/cluster"
)

type FakeCluster struct {
	AddDatabaseParserStub        func(string, cluster.DatabaseParser)
	addDatabaseParserMutex       sync.RWMutex
	addDatabaseParserArgsForCall []struct {
		arg1 string
		arg2 cluster.DatabaseParser
	}
	AddSyncableParserStub        func(string, cluster.SyncableParser)
	addSyncableParserMutex       sync.RWMutex
	addSyncableParserArgsForCall []struct {
		arg1 string
		arg2 cluster.SyncableParser
	}
	AppliedIndexStub        func() uint64
	appliedIndexMutex       sync.RWMutex
	appliedIndexArgsForCall []struct {
	}
	appliedIndexReturns struct {
		result1 uint64
	}
	appliedIndexReturnsOnCall map[int]struct {
		result1 uint64
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DatabaseVersionStub        func(string, uint64) (*cluster.Configuration, error)
	databaseVersionMutex       sync.RWMutex
	databaseVersionArgsForCall []struct {
		arg1 string
		arg2 uint64
	}
	databaseVersionReturns struct {
		result1 *cluster.Configuration
		result2 error
	}
	databaseVersionReturnsOnCall map[int]struct {
		result1 *cluster.Configuration
		result2 error
	}
	DatabaseVersionsStub        func(string) ([]cluster.VersionInfo, error)
	databaseVersionsMutex       sync.RWMutex
	databaseVersionsArgsForCall []struct {
		arg1 string
	}
	databaseVersionsReturns struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	databaseVersionsReturnsOnCall map[int]struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	DatabasesStub        func() ([]*cluster.Configuration, error)
	databasesMutex       sync.RWMutex
	databasesArgsForCall []struct {
	}
	databasesReturns struct {
		result1 []*cluster.Configuration
		result2 error
	}
	databasesReturnsOnCall map[int]struct {
		result1 []*cluster.Configuration
		result2 error
	}
	IngestStub        func(context.Context, string, cluster.Ingestable) error
	ingestMutex       sync.RWMutex
	ingestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 cluster.Ingestable
	}
	ingestReturns struct {
		result1 error
	}
	ingestReturnsOnCall map[int]struct {
		result1 error
	}
	IngestableVersionStub        func(string, uint64) (*cluster.Configuration, error)
	ingestableVersionMutex       sync.RWMutex
	ingestableVersionArgsForCall []struct {
		arg1 string
		arg2 uint64
	}
	ingestableVersionReturns struct {
		result1 *cluster.Configuration
		result2 error
	}
	ingestableVersionReturnsOnCall map[int]struct {
		result1 *cluster.Configuration
		result2 error
	}
	IngestableVersionsStub        func(string) ([]cluster.VersionInfo, error)
	ingestableVersionsMutex       sync.RWMutex
	ingestableVersionsArgsForCall []struct {
		arg1 string
	}
	ingestableVersionsReturns struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	ingestableVersionsReturnsOnCall map[int]struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	IngestablesStub        func() ([]*cluster.Configuration, error)
	ingestablesMutex       sync.RWMutex
	ingestablesArgsForCall []struct {
	}
	ingestablesReturns struct {
		result1 []*cluster.Configuration
		result2 error
	}
	ingestablesReturnsOnCall map[int]struct {
		result1 []*cluster.Configuration
		result2 error
	}
	LeaderStub        func() uint64
	leaderMutex       sync.RWMutex
	leaderArgsForCall []struct {
	}
	leaderReturns struct {
		result1 uint64
	}
	leaderReturnsOnCall map[int]struct {
		result1 uint64
	}
	ProposalsStub        func(uint64, ...string) ([]*cluster.Proposal, error)
	proposalsMutex       sync.RWMutex
	proposalsArgsForCall []struct {
		arg1 uint64
		arg2 []string
	}
	proposalsReturns struct {
		result1 []*cluster.Proposal
		result2 error
	}
	proposalsReturnsOnCall map[int]struct {
		result1 []*cluster.Proposal
		result2 error
	}
	ProposeStub        func(context.Context, *cluster.Proposal) error
	proposeMutex       sync.RWMutex
	proposeArgsForCall []struct {
		arg1 context.Context
		arg2 *cluster.Proposal
	}
	proposeReturns struct {
		result1 error
	}
	proposeReturnsOnCall map[int]struct {
		result1 error
	}
	ProposeDatabaseStub        func(context.Context, *cluster.Configuration) error
	proposeDatabaseMutex       sync.RWMutex
	proposeDatabaseArgsForCall []struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}
	proposeDatabaseReturns struct {
		result1 error
	}
	proposeDatabaseReturnsOnCall map[int]struct {
		result1 error
	}
	ProposeDeleteTypeStub        func(context.Context, string) error
	proposeDeleteTypeMutex       sync.RWMutex
	proposeDeleteTypeArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	proposeDeleteTypeReturns struct {
		result1 error
	}
	proposeDeleteTypeReturnsOnCall map[int]struct {
		result1 error
	}
	ProposeIngestableStub        func(context.Context, *cluster.Configuration) error
	proposeIngestableMutex       sync.RWMutex
	proposeIngestableArgsForCall []struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}
	proposeIngestableReturns struct {
		result1 error
	}
	proposeIngestableReturnsOnCall map[int]struct {
		result1 error
	}
	ProposeSyncableStub        func(context.Context, *cluster.Configuration) error
	proposeSyncableMutex       sync.RWMutex
	proposeSyncableArgsForCall []struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}
	proposeSyncableReturns struct {
		result1 error
	}
	proposeSyncableReturnsOnCall map[int]struct {
		result1 error
	}
	ProposeTypeStub        func(context.Context, *cluster.Configuration) error
	proposeTypeMutex       sync.RWMutex
	proposeTypeArgsForCall []struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}
	proposeTypeReturns struct {
		result1 error
	}
	proposeTypeReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveTypeStub        func(cluster.TypeRef) (*cluster.Type, error)
	resolveTypeMutex       sync.RWMutex
	resolveTypeArgsForCall []struct {
		arg1 cluster.TypeRef
	}
	resolveTypeReturns struct {
		result1 *cluster.Type
		result2 error
	}
	resolveTypeReturnsOnCall map[int]struct {
		result1 *cluster.Type
		result2 error
	}
	SyncStub        func(context.Context, string, cluster.Syncable) error
	syncMutex       sync.RWMutex
	syncArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 cluster.Syncable
	}
	syncReturns struct {
		result1 error
	}
	syncReturnsOnCall map[int]struct {
		result1 error
	}
	SyncableVersionStub        func(string, uint64) (*cluster.Configuration, error)
	syncableVersionMutex       sync.RWMutex
	syncableVersionArgsForCall []struct {
		arg1 string
		arg2 uint64
	}
	syncableVersionReturns struct {
		result1 *cluster.Configuration
		result2 error
	}
	syncableVersionReturnsOnCall map[int]struct {
		result1 *cluster.Configuration
		result2 error
	}
	SyncableVersionsStub        func(string) ([]cluster.VersionInfo, error)
	syncableVersionsMutex       sync.RWMutex
	syncableVersionsArgsForCall []struct {
		arg1 string
	}
	syncableVersionsReturns struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	syncableVersionsReturnsOnCall map[int]struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	SyncablesStub        func() ([]*cluster.Configuration, error)
	syncablesMutex       sync.RWMutex
	syncablesArgsForCall []struct {
	}
	syncablesReturns struct {
		result1 []*cluster.Configuration
		result2 error
	}
	syncablesReturnsOnCall map[int]struct {
		result1 []*cluster.Configuration
		result2 error
	}
	TypeGraphStub        func(string, time.Time, time.Time) ([]cluster.TimePoint, error)
	typeGraphMutex       sync.RWMutex
	typeGraphArgsForCall []struct {
		arg1 string
		arg2 time.Time
		arg3 time.Time
	}
	typeGraphReturns struct {
		result1 []cluster.TimePoint
		result2 error
	}
	typeGraphReturnsOnCall map[int]struct {
		result1 []cluster.TimePoint
		result2 error
	}
	TypeVersionStub        func(string, uint64) (*cluster.Configuration, error)
	typeVersionMutex       sync.RWMutex
	typeVersionArgsForCall []struct {
		arg1 string
		arg2 uint64
	}
	typeVersionReturns struct {
		result1 *cluster.Configuration
		result2 error
	}
	typeVersionReturnsOnCall map[int]struct {
		result1 *cluster.Configuration
		result2 error
	}
	TypeVersionsStub        func(string) ([]cluster.VersionInfo, error)
	typeVersionsMutex       sync.RWMutex
	typeVersionsArgsForCall []struct {
		arg1 string
	}
	typeVersionsReturns struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	typeVersionsReturnsOnCall map[int]struct {
		result1 []cluster.VersionInfo
		result2 error
	}
	TypesStub        func() ([]*cluster.Configuration, error)
	typesMutex       sync.RWMutex
	typesArgsForCall []struct {
	}
	typesReturns struct {
		result1 []*cluster.Configuration
		result2 error
	}
	typesReturnsOnCall map[int]struct {
		result1 []*cluster.Configuration
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCluster) AddDatabaseParser(arg1 string, arg2 cluster.DatabaseParser) {
	fake.addDatabaseParserMutex.Lock()
	fake.addDatabaseParserArgsForCall = append(fake.addDatabaseParserArgsForCall, struct {
		arg1 string
		arg2 cluster.DatabaseParser
	}{arg1, arg2})
	stub := fake.AddDatabaseParserStub
	fake.recordInvocation("AddDatabaseParser", []interface{}{arg1, arg2})
	fake.addDatabaseParserMutex.Unlock()
	if stub != nil {
		fake.AddDatabaseParserStub(arg1, arg2)
	}
}

func (fake *FakeCluster) AddDatabaseParserCallCount() int {
	fake.addDatabaseParserMutex.RLock()
	defer fake.addDatabaseParserMutex.RUnlock()
	return len(fake.addDatabaseParserArgsForCall)
}

func (fake *FakeCluster) AddDatabaseParserCalls(stub func(string, cluster.DatabaseParser)) {
	fake.addDatabaseParserMutex.Lock()
	defer fake.addDatabaseParserMutex.Unlock()
	fake.AddDatabaseParserStub = stub
}

func (fake *FakeCluster) AddDatabaseParserArgsForCall(i int) (string, cluster.DatabaseParser) {
	fake.addDatabaseParserMutex.RLock()
	defer fake.addDatabaseParserMutex.RUnlock()
	argsForCall := fake.addDatabaseParserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) AddSyncableParser(arg1 string, arg2 cluster.SyncableParser) {
	fake.addSyncableParserMutex.Lock()
	fake.addSyncableParserArgsForCall = append(fake.addSyncableParserArgsForCall, struct {
		arg1 string
		arg2 cluster.SyncableParser
	}{arg1, arg2})
	stub := fake.AddSyncableParserStub
	fake.recordInvocation("AddSyncableParser", []interface{}{arg1, arg2})
	fake.addSyncableParserMutex.Unlock()
	if stub != nil {
		fake.AddSyncableParserStub(arg1, arg2)
	}
}

func (fake *FakeCluster) AddSyncableParserCallCount() int {
	fake.addSyncableParserMutex.RLock()
	defer fake.addSyncableParserMutex.RUnlock()
	return len(fake.addSyncableParserArgsForCall)
}

func (fake *FakeCluster) AddSyncableParserCalls(stub func(string, cluster.SyncableParser)) {
	fake.addSyncableParserMutex.Lock()
	defer fake.addSyncableParserMutex.Unlock()
	fake.AddSyncableParserStub = stub
}

func (fake *FakeCluster) AddSyncableParserArgsForCall(i int) (string, cluster.SyncableParser) {
	fake.addSyncableParserMutex.RLock()
	defer fake.addSyncableParserMutex.RUnlock()
	argsForCall := fake.addSyncableParserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) AppliedIndex() uint64 {
	fake.appliedIndexMutex.Lock()
	ret, specificReturn := fake.appliedIndexReturnsOnCall[len(fake.appliedIndexArgsForCall)]
	fake.appliedIndexArgsForCall = append(fake.appliedIndexArgsForCall, struct {
	}{})
	stub := fake.AppliedIndexStub
	fakeReturns := fake.appliedIndexReturns
	fake.recordInvocation("AppliedIndex", []interface{}{})
	fake.appliedIndexMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) AppliedIndexCallCount() int {
	fake.appliedIndexMutex.RLock()
	defer fake.appliedIndexMutex.RUnlock()
	return len(fake.appliedIndexArgsForCall)
}

func (fake *FakeCluster) AppliedIndexCalls(stub func() uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = stub
}

func (fake *FakeCluster) AppliedIndexReturns(result1 uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = nil
	fake.appliedIndexReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) AppliedIndexReturnsOnCall(i int, result1 uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = nil
	if fake.appliedIndexReturnsOnCall == nil {
		fake.appliedIndexReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.appliedIndexReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeCluster) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeCluster) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) DatabaseVersion(arg1 string, arg2 uint64) (*cluster.Configuration, error) {
	fake.databaseVersionMutex.Lock()
	ret, specificReturn := fake.databaseVersionReturnsOnCall[len(fake.databaseVersionArgsForCall)]
	fake.databaseVersionArgsForCall = append(fake.databaseVersionArgsForCall, struct {
		arg1 string
		arg2 uint64
	}{arg1, arg2})
	stub := fake.DatabaseVersionStub
	fakeReturns := fake.databaseVersionReturns
	fake.recordInvocation("DatabaseVersion", []interface{}{arg1, arg2})
	fake.databaseVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) DatabaseVersionCallCount() int {
	fake.databaseVersionMutex.RLock()
	defer fake.databaseVersionMutex.RUnlock()
	return len(fake.databaseVersionArgsForCall)
}

func (fake *FakeCluster) DatabaseVersionCalls(stub func(string, uint64) (*cluster.Configuration, error)) {
	fake.databaseVersionMutex.Lock()
	defer fake.databaseVersionMutex.Unlock()
	fake.DatabaseVersionStub = stub
}

func (fake *FakeCluster) DatabaseVersionArgsForCall(i int) (string, uint64) {
	fake.databaseVersionMutex.RLock()
	defer fake.databaseVersionMutex.RUnlock()
	argsForCall := fake.databaseVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) DatabaseVersionReturns(result1 *cluster.Configuration, result2 error) {
	fake.databaseVersionMutex.Lock()
	defer fake.databaseVersionMutex.Unlock()
	fake.DatabaseVersionStub = nil
	fake.databaseVersionReturns = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) DatabaseVersionReturnsOnCall(i int, result1 *cluster.Configuration, result2 error) {
	fake.databaseVersionMutex.Lock()
	defer fake.databaseVersionMutex.Unlock()
	fake.DatabaseVersionStub = nil
	if fake.databaseVersionReturnsOnCall == nil {
		fake.databaseVersionReturnsOnCall = make(map[int]struct {
			result1 *cluster.Configuration
			result2 error
		})
	}
	fake.databaseVersionReturnsOnCall[i] = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) DatabaseVersions(arg1 string) ([]cluster.VersionInfo, error) {
	fake.databaseVersionsMutex.Lock()
	ret, specificReturn := fake.databaseVersionsReturnsOnCall[len(fake.databaseVersionsArgsForCall)]
	fake.databaseVersionsArgsForCall = append(fake.databaseVersionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DatabaseVersionsStub
	fakeReturns := fake.databaseVersionsReturns
	fake.recordInvocation("DatabaseVersions", []interface{}{arg1})
	fake.databaseVersionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) DatabaseVersionsCallCount() int {
	fake.databaseVersionsMutex.RLock()
	defer fake.databaseVersionsMutex.RUnlock()
	return len(fake.databaseVersionsArgsForCall)
}

func (fake *FakeCluster) DatabaseVersionsCalls(stub func(string) ([]cluster.VersionInfo, error)) {
	fake.databaseVersionsMutex.Lock()
	defer fake.databaseVersionsMutex.Unlock()
	fake.DatabaseVersionsStub = stub
}

func (fake *FakeCluster) DatabaseVersionsArgsForCall(i int) string {
	fake.databaseVersionsMutex.RLock()
	defer fake.databaseVersionsMutex.RUnlock()
	argsForCall := fake.databaseVersionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) DatabaseVersionsReturns(result1 []cluster.VersionInfo, result2 error) {
	fake.databaseVersionsMutex.Lock()
	defer fake.databaseVersionsMutex.Unlock()
	fake.DatabaseVersionsStub = nil
	fake.databaseVersionsReturns = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) DatabaseVersionsReturnsOnCall(i int, result1 []cluster.VersionInfo, result2 error) {
	fake.databaseVersionsMutex.Lock()
	defer fake.databaseVersionsMutex.Unlock()
	fake.DatabaseVersionsStub = nil
	if fake.databaseVersionsReturnsOnCall == nil {
		fake.databaseVersionsReturnsOnCall = make(map[int]struct {
			result1 []cluster.VersionInfo
			result2 error
		})
	}
	fake.databaseVersionsReturnsOnCall[i] = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Databases() ([]*cluster.Configuration, error) {
	fake.databasesMutex.Lock()
	ret, specificReturn := fake.databasesReturnsOnCall[len(fake.databasesArgsForCall)]
	fake.databasesArgsForCall = append(fake.databasesArgsForCall, struct {
	}{})
	stub := fake.DatabasesStub
	fakeReturns := fake.databasesReturns
	fake.recordInvocation("Databases", []interface{}{})
	fake.databasesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) DatabasesCallCount() int {
	fake.databasesMutex.RLock()
	defer fake.databasesMutex.RUnlock()
	return len(fake.databasesArgsForCall)
}

func (fake *FakeCluster) DatabasesCalls(stub func() ([]*cluster.Configuration, error)) {
	fake.databasesMutex.Lock()
	defer fake.databasesMutex.Unlock()
	fake.DatabasesStub = stub
}

func (fake *FakeCluster) DatabasesReturns(result1 []*cluster.Configuration, result2 error) {
	fake.databasesMutex.Lock()
	defer fake.databasesMutex.Unlock()
	fake.DatabasesStub = nil
	fake.databasesReturns = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) DatabasesReturnsOnCall(i int, result1 []*cluster.Configuration, result2 error) {
	fake.databasesMutex.Lock()
	defer fake.databasesMutex.Unlock()
	fake.DatabasesStub = nil
	if fake.databasesReturnsOnCall == nil {
		fake.databasesReturnsOnCall = make(map[int]struct {
			result1 []*cluster.Configuration
			result2 error
		})
	}
	fake.databasesReturnsOnCall[i] = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Ingest(arg1 context.Context, arg2 string, arg3 cluster.Ingestable) error {
	fake.ingestMutex.Lock()
	ret, specificReturn := fake.ingestReturnsOnCall[len(fake.ingestArgsForCall)]
	fake.ingestArgsForCall = append(fake.ingestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 cluster.Ingestable
	}{arg1, arg2, arg3})
	stub := fake.IngestStub
	fakeReturns := fake.ingestReturns
	fake.recordInvocation("Ingest", []interface{}{arg1, arg2, arg3})
	fake.ingestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) IngestCallCount() int {
	fake.ingestMutex.RLock()
	defer fake.ingestMutex.RUnlock()
	return len(fake.ingestArgsForCall)
}

func (fake *FakeCluster) IngestCalls(stub func(context.Context, string, cluster.Ingestable) error) {
	fake.ingestMutex.Lock()
	defer fake.ingestMutex.Unlock()
	fake.IngestStub = stub
}

func (fake *FakeCluster) IngestArgsForCall(i int) (context.Context, string, cluster.Ingestable) {
	fake.ingestMutex.RLock()
	defer fake.ingestMutex.RUnlock()
	argsForCall := fake.ingestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCluster) IngestReturns(result1 error) {
	fake.ingestMutex.Lock()
	defer fake.ingestMutex.Unlock()
	fake.IngestStub = nil
	fake.ingestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) IngestReturnsOnCall(i int, result1 error) {
	fake.ingestMutex.Lock()
	defer fake.ingestMutex.Unlock()
	fake.IngestStub = nil
	if fake.ingestReturnsOnCall == nil {
		fake.ingestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.ingestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) IngestableVersion(arg1 string, arg2 uint64) (*cluster.Configuration, error) {
	fake.ingestableVersionMutex.Lock()
	ret, specificReturn := fake.ingestableVersionReturnsOnCall[len(fake.ingestableVersionArgsForCall)]
	fake.ingestableVersionArgsForCall = append(fake.ingestableVersionArgsForCall, struct {
		arg1 string
		arg2 uint64
	}{arg1, arg2})
	stub := fake.IngestableVersionStub
	fakeReturns := fake.ingestableVersionReturns
	fake.recordInvocation("IngestableVersion", []interface{}{arg1, arg2})
	fake.ingestableVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) IngestableVersionCallCount() int {
	fake.ingestableVersionMutex.RLock()
	defer fake.ingestableVersionMutex.RUnlock()
	return len(fake.ingestableVersionArgsForCall)
}

func (fake *FakeCluster) IngestableVersionCalls(stub func(string, uint64) (*cluster.Configuration, error)) {
	fake.ingestableVersionMutex.Lock()
	defer fake.ingestableVersionMutex.Unlock()
	fake.IngestableVersionStub = stub
}

func (fake *FakeCluster) IngestableVersionArgsForCall(i int) (string, uint64) {
	fake.ingestableVersionMutex.RLock()
	defer fake.ingestableVersionMutex.RUnlock()
	argsForCall := fake.ingestableVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) IngestableVersionReturns(result1 *cluster.Configuration, result2 error) {
	fake.ingestableVersionMutex.Lock()
	defer fake.ingestableVersionMutex.Unlock()
	fake.IngestableVersionStub = nil
	fake.ingestableVersionReturns = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) IngestableVersionReturnsOnCall(i int, result1 *cluster.Configuration, result2 error) {
	fake.ingestableVersionMutex.Lock()
	defer fake.ingestableVersionMutex.Unlock()
	fake.IngestableVersionStub = nil
	if fake.ingestableVersionReturnsOnCall == nil {
		fake.ingestableVersionReturnsOnCall = make(map[int]struct {
			result1 *cluster.Configuration
			result2 error
		})
	}
	fake.ingestableVersionReturnsOnCall[i] = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) IngestableVersions(arg1 string) ([]cluster.VersionInfo, error) {
	fake.ingestableVersionsMutex.Lock()
	ret, specificReturn := fake.ingestableVersionsReturnsOnCall[len(fake.ingestableVersionsArgsForCall)]
	fake.ingestableVersionsArgsForCall = append(fake.ingestableVersionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IngestableVersionsStub
	fakeReturns := fake.ingestableVersionsReturns
	fake.recordInvocation("IngestableVersions", []interface{}{arg1})
	fake.ingestableVersionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) IngestableVersionsCallCount() int {
	fake.ingestableVersionsMutex.RLock()
	defer fake.ingestableVersionsMutex.RUnlock()
	return len(fake.ingestableVersionsArgsForCall)
}

func (fake *FakeCluster) IngestableVersionsCalls(stub func(string) ([]cluster.VersionInfo, error)) {
	fake.ingestableVersionsMutex.Lock()
	defer fake.ingestableVersionsMutex.Unlock()
	fake.IngestableVersionsStub = stub
}

func (fake *FakeCluster) IngestableVersionsArgsForCall(i int) string {
	fake.ingestableVersionsMutex.RLock()
	defer fake.ingestableVersionsMutex.RUnlock()
	argsForCall := fake.ingestableVersionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) IngestableVersionsReturns(result1 []cluster.VersionInfo, result2 error) {
	fake.ingestableVersionsMutex.Lock()
	defer fake.ingestableVersionsMutex.Unlock()
	fake.IngestableVersionsStub = nil
	fake.ingestableVersionsReturns = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) IngestableVersionsReturnsOnCall(i int, result1 []cluster.VersionInfo, result2 error) {
	fake.ingestableVersionsMutex.Lock()
	defer fake.ingestableVersionsMutex.Unlock()
	fake.IngestableVersionsStub = nil
	if fake.ingestableVersionsReturnsOnCall == nil {
		fake.ingestableVersionsReturnsOnCall = make(map[int]struct {
			result1 []cluster.VersionInfo
			result2 error
		})
	}
	fake.ingestableVersionsReturnsOnCall[i] = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Ingestables() ([]*cluster.Configuration, error) {
	fake.ingestablesMutex.Lock()
	ret, specificReturn := fake.ingestablesReturnsOnCall[len(fake.ingestablesArgsForCall)]
	fake.ingestablesArgsForCall = append(fake.ingestablesArgsForCall, struct {
	}{})
	stub := fake.IngestablesStub
	fakeReturns := fake.ingestablesReturns
	fake.recordInvocation("Ingestables", []interface{}{})
	fake.ingestablesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) IngestablesCallCount() int {
	fake.ingestablesMutex.RLock()
	defer fake.ingestablesMutex.RUnlock()
	return len(fake.ingestablesArgsForCall)
}

func (fake *FakeCluster) IngestablesCalls(stub func() ([]*cluster.Configuration, error)) {
	fake.ingestablesMutex.Lock()
	defer fake.ingestablesMutex.Unlock()
	fake.IngestablesStub = stub
}

func (fake *FakeCluster) IngestablesReturns(result1 []*cluster.Configuration, result2 error) {
	fake.ingestablesMutex.Lock()
	defer fake.ingestablesMutex.Unlock()
	fake.IngestablesStub = nil
	fake.ingestablesReturns = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) IngestablesReturnsOnCall(i int, result1 []*cluster.Configuration, result2 error) {
	fake.ingestablesMutex.Lock()
	defer fake.ingestablesMutex.Unlock()
	fake.IngestablesStub = nil
	if fake.ingestablesReturnsOnCall == nil {
		fake.ingestablesReturnsOnCall = make(map[int]struct {
			result1 []*cluster.Configuration
			result2 error
		})
	}
	fake.ingestablesReturnsOnCall[i] = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Leader() uint64 {
	fake.leaderMutex.Lock()
	ret, specificReturn := fake.leaderReturnsOnCall[len(fake.leaderArgsForCall)]
	fake.leaderArgsForCall = append(fake.leaderArgsForCall, struct {
	}{})
	stub := fake.LeaderStub
	fakeReturns := fake.leaderReturns
	fake.recordInvocation("Leader", []interface{}{})
	fake.leaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) LeaderCallCount() int {
	fake.leaderMutex.RLock()
	defer fake.leaderMutex.RUnlock()
	return len(fake.leaderArgsForCall)
}

func (fake *FakeCluster) LeaderCalls(stub func() uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = stub
}

func (fake *FakeCluster) LeaderReturns(result1 uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	fake.leaderReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) LeaderReturnsOnCall(i int, result1 uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	if fake.leaderReturnsOnCall == nil {
		fake.leaderReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.leaderReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) Proposals(arg1 uint64, arg2 ...string) ([]*cluster.Proposal, error) {
	fake.proposalsMutex.Lock()
	ret, specificReturn := fake.proposalsReturnsOnCall[len(fake.proposalsArgsForCall)]
	fake.proposalsArgsForCall = append(fake.proposalsArgsForCall, struct {
		arg1 uint64
		arg2 []string
	}{arg1, arg2})
	stub := fake.ProposalsStub
	fakeReturns := fake.proposalsReturns
	fake.recordInvocation("Proposals", []interface{}{arg1, arg2})
	fake.proposalsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) ProposalsCallCount() int {
	fake.proposalsMutex.RLock()
	defer fake.proposalsMutex.RUnlock()
	return len(fake.proposalsArgsForCall)
}

func (fake *FakeCluster) ProposalsCalls(stub func(uint64, ...string) ([]*cluster.Proposal, error)) {
	fake.proposalsMutex.Lock()
	defer fake.proposalsMutex.Unlock()
	fake.ProposalsStub = stub
}

func (fake *FakeCluster) ProposalsArgsForCall(i int) (uint64, []string) {
	fake.proposalsMutex.RLock()
	defer fake.proposalsMutex.RUnlock()
	argsForCall := fake.proposalsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposalsReturns(result1 []*cluster.Proposal, result2 error) {
	fake.proposalsMutex.Lock()
	defer fake.proposalsMutex.Unlock()
	fake.ProposalsStub = nil
	fake.proposalsReturns = struct {
		result1 []*cluster.Proposal
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) ProposalsReturnsOnCall(i int, result1 []*cluster.Proposal, result2 error) {
	fake.proposalsMutex.Lock()
	defer fake.proposalsMutex.Unlock()
	fake.ProposalsStub = nil
	if fake.proposalsReturnsOnCall == nil {
		fake.proposalsReturnsOnCall = make(map[int]struct {
			result1 []*cluster.Proposal
			result2 error
		})
	}
	fake.proposalsReturnsOnCall[i] = struct {
		result1 []*cluster.Proposal
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Propose(arg1 context.Context, arg2 *cluster.Proposal) error {
	fake.proposeMutex.Lock()
	ret, specificReturn := fake.proposeReturnsOnCall[len(fake.proposeArgsForCall)]
	fake.proposeArgsForCall = append(fake.proposeArgsForCall, struct {
		arg1 context.Context
		arg2 *cluster.Proposal
	}{arg1, arg2})
	stub := fake.ProposeStub
	fakeReturns := fake.proposeReturns
	fake.recordInvocation("Propose", []interface{}{arg1, arg2})
	fake.proposeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeCallCount() int {
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	return len(fake.proposeArgsForCall)
}

func (fake *FakeCluster) ProposeCalls(stub func(context.Context, *cluster.Proposal) error) {
	fake.proposeMutex.Lock()
	defer fake.proposeMutex.Unlock()
	fake.ProposeStub = stub
}

func (fake *FakeCluster) ProposeArgsForCall(i int) (context.Context, *cluster.Proposal) {
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	argsForCall := fake.proposeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeReturns(result1 error) {
	fake.proposeMutex.Lock()
	defer fake.proposeMutex.Unlock()
	fake.ProposeStub = nil
	fake.proposeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeReturnsOnCall(i int, result1 error) {
	fake.proposeMutex.Lock()
	defer fake.proposeMutex.Unlock()
	fake.ProposeStub = nil
	if fake.proposeReturnsOnCall == nil {
		fake.proposeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeDatabase(arg1 context.Context, arg2 *cluster.Configuration) error {
	fake.proposeDatabaseMutex.Lock()
	ret, specificReturn := fake.proposeDatabaseReturnsOnCall[len(fake.proposeDatabaseArgsForCall)]
	fake.proposeDatabaseArgsForCall = append(fake.proposeDatabaseArgsForCall, struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}{arg1, arg2})
	stub := fake.ProposeDatabaseStub
	fakeReturns := fake.proposeDatabaseReturns
	fake.recordInvocation("ProposeDatabase", []interface{}{arg1, arg2})
	fake.proposeDatabaseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeDatabaseCallCount() int {
	fake.proposeDatabaseMutex.RLock()
	defer fake.proposeDatabaseMutex.RUnlock()
	return len(fake.proposeDatabaseArgsForCall)
}

func (fake *FakeCluster) ProposeDatabaseCalls(stub func(context.Context, *cluster.Configuration) error) {
	fake.proposeDatabaseMutex.Lock()
	defer fake.proposeDatabaseMutex.Unlock()
	fake.ProposeDatabaseStub = stub
}

func (fake *FakeCluster) ProposeDatabaseArgsForCall(i int) (context.Context, *cluster.Configuration) {
	fake.proposeDatabaseMutex.RLock()
	defer fake.proposeDatabaseMutex.RUnlock()
	argsForCall := fake.proposeDatabaseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeDatabaseReturns(result1 error) {
	fake.proposeDatabaseMutex.Lock()
	defer fake.proposeDatabaseMutex.Unlock()
	fake.ProposeDatabaseStub = nil
	fake.proposeDatabaseReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeDatabaseReturnsOnCall(i int, result1 error) {
	fake.proposeDatabaseMutex.Lock()
	defer fake.proposeDatabaseMutex.Unlock()
	fake.ProposeDatabaseStub = nil
	if fake.proposeDatabaseReturnsOnCall == nil {
		fake.proposeDatabaseReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeDatabaseReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeDeleteType(arg1 context.Context, arg2 string) error {
	fake.proposeDeleteTypeMutex.Lock()
	ret, specificReturn := fake.proposeDeleteTypeReturnsOnCall[len(fake.proposeDeleteTypeArgsForCall)]
	fake.proposeDeleteTypeArgsForCall = append(fake.proposeDeleteTypeArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ProposeDeleteTypeStub
	fakeReturns := fake.proposeDeleteTypeReturns
	fake.recordInvocation("ProposeDeleteType", []interface{}{arg1, arg2})
	fake.proposeDeleteTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeDeleteTypeCallCount() int {
	fake.proposeDeleteTypeMutex.RLock()
	defer fake.proposeDeleteTypeMutex.RUnlock()
	return len(fake.proposeDeleteTypeArgsForCall)
}

func (fake *FakeCluster) ProposeDeleteTypeCalls(stub func(context.Context, string) error) {
	fake.proposeDeleteTypeMutex.Lock()
	defer fake.proposeDeleteTypeMutex.Unlock()
	fake.ProposeDeleteTypeStub = stub
}

func (fake *FakeCluster) ProposeDeleteTypeArgsForCall(i int) (context.Context, string) {
	fake.proposeDeleteTypeMutex.RLock()
	defer fake.proposeDeleteTypeMutex.RUnlock()
	argsForCall := fake.proposeDeleteTypeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeDeleteTypeReturns(result1 error) {
	fake.proposeDeleteTypeMutex.Lock()
	defer fake.proposeDeleteTypeMutex.Unlock()
	fake.ProposeDeleteTypeStub = nil
	fake.proposeDeleteTypeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeDeleteTypeReturnsOnCall(i int, result1 error) {
	fake.proposeDeleteTypeMutex.Lock()
	defer fake.proposeDeleteTypeMutex.Unlock()
	fake.ProposeDeleteTypeStub = nil
	if fake.proposeDeleteTypeReturnsOnCall == nil {
		fake.proposeDeleteTypeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeDeleteTypeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeIngestable(arg1 context.Context, arg2 *cluster.Configuration) error {
	fake.proposeIngestableMutex.Lock()
	ret, specificReturn := fake.proposeIngestableReturnsOnCall[len(fake.proposeIngestableArgsForCall)]
	fake.proposeIngestableArgsForCall = append(fake.proposeIngestableArgsForCall, struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}{arg1, arg2})
	stub := fake.ProposeIngestableStub
	fakeReturns := fake.proposeIngestableReturns
	fake.recordInvocation("ProposeIngestable", []interface{}{arg1, arg2})
	fake.proposeIngestableMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeIngestableCallCount() int {
	fake.proposeIngestableMutex.RLock()
	defer fake.proposeIngestableMutex.RUnlock()
	return len(fake.proposeIngestableArgsForCall)
}

func (fake *FakeCluster) ProposeIngestableCalls(stub func(context.Context, *cluster.Configuration) error) {
	fake.proposeIngestableMutex.Lock()
	defer fake.proposeIngestableMutex.Unlock()
	fake.ProposeIngestableStub = stub
}

func (fake *FakeCluster) ProposeIngestableArgsForCall(i int) (context.Context, *cluster.Configuration) {
	fake.proposeIngestableMutex.RLock()
	defer fake.proposeIngestableMutex.RUnlock()
	argsForCall := fake.proposeIngestableArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeIngestableReturns(result1 error) {
	fake.proposeIngestableMutex.Lock()
	defer fake.proposeIngestableMutex.Unlock()
	fake.ProposeIngestableStub = nil
	fake.proposeIngestableReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeIngestableReturnsOnCall(i int, result1 error) {
	fake.proposeIngestableMutex.Lock()
	defer fake.proposeIngestableMutex.Unlock()
	fake.ProposeIngestableStub = nil
	if fake.proposeIngestableReturnsOnCall == nil {
		fake.proposeIngestableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeIngestableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeSyncable(arg1 context.Context, arg2 *cluster.Configuration) error {
	fake.proposeSyncableMutex.Lock()
	ret, specificReturn := fake.proposeSyncableReturnsOnCall[len(fake.proposeSyncableArgsForCall)]
	fake.proposeSyncableArgsForCall = append(fake.proposeSyncableArgsForCall, struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}{arg1, arg2})
	stub := fake.ProposeSyncableStub
	fakeReturns := fake.proposeSyncableReturns
	fake.recordInvocation("ProposeSyncable", []interface{}{arg1, arg2})
	fake.proposeSyncableMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeSyncableCallCount() int {
	fake.proposeSyncableMutex.RLock()
	defer fake.proposeSyncableMutex.RUnlock()
	return len(fake.proposeSyncableArgsForCall)
}

func (fake *FakeCluster) ProposeSyncableCalls(stub func(context.Context, *cluster.Configuration) error) {
	fake.proposeSyncableMutex.Lock()
	defer fake.proposeSyncableMutex.Unlock()
	fake.ProposeSyncableStub = stub
}

func (fake *FakeCluster) ProposeSyncableArgsForCall(i int) (context.Context, *cluster.Configuration) {
	fake.proposeSyncableMutex.RLock()
	defer fake.proposeSyncableMutex.RUnlock()
	argsForCall := fake.proposeSyncableArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeSyncableReturns(result1 error) {
	fake.proposeSyncableMutex.Lock()
	defer fake.proposeSyncableMutex.Unlock()
	fake.ProposeSyncableStub = nil
	fake.proposeSyncableReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeSyncableReturnsOnCall(i int, result1 error) {
	fake.proposeSyncableMutex.Lock()
	defer fake.proposeSyncableMutex.Unlock()
	fake.ProposeSyncableStub = nil
	if fake.proposeSyncableReturnsOnCall == nil {
		fake.proposeSyncableReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeSyncableReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeType(arg1 context.Context, arg2 *cluster.Configuration) error {
	fake.proposeTypeMutex.Lock()
	ret, specificReturn := fake.proposeTypeReturnsOnCall[len(fake.proposeTypeArgsForCall)]
	fake.proposeTypeArgsForCall = append(fake.proposeTypeArgsForCall, struct {
		arg1 context.Context
		arg2 *cluster.Configuration
	}{arg1, arg2})
	stub := fake.ProposeTypeStub
	fakeReturns := fake.proposeTypeReturns
	fake.recordInvocation("ProposeType", []interface{}{arg1, arg2})
	fake.proposeTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ProposeTypeCallCount() int {
	fake.proposeTypeMutex.RLock()
	defer fake.proposeTypeMutex.RUnlock()
	return len(fake.proposeTypeArgsForCall)
}

func (fake *FakeCluster) ProposeTypeCalls(stub func(context.Context, *cluster.Configuration) error) {
	fake.proposeTypeMutex.Lock()
	defer fake.proposeTypeMutex.Unlock()
	fake.ProposeTypeStub = stub
}

func (fake *FakeCluster) ProposeTypeArgsForCall(i int) (context.Context, *cluster.Configuration) {
	fake.proposeTypeMutex.RLock()
	defer fake.proposeTypeMutex.RUnlock()
	argsForCall := fake.proposeTypeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) ProposeTypeReturns(result1 error) {
	fake.proposeTypeMutex.Lock()
	defer fake.proposeTypeMutex.Unlock()
	fake.ProposeTypeStub = nil
	fake.proposeTypeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ProposeTypeReturnsOnCall(i int, result1 error) {
	fake.proposeTypeMutex.Lock()
	defer fake.proposeTypeMutex.Unlock()
	fake.ProposeTypeStub = nil
	if fake.proposeTypeReturnsOnCall == nil {
		fake.proposeTypeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.proposeTypeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) ResolveType(arg1 cluster.TypeRef) (*cluster.Type, error) {
	fake.resolveTypeMutex.Lock()
	ret, specificReturn := fake.resolveTypeReturnsOnCall[len(fake.resolveTypeArgsForCall)]
	fake.resolveTypeArgsForCall = append(fake.resolveTypeArgsForCall, struct {
		arg1 cluster.TypeRef
	}{arg1})
	stub := fake.ResolveTypeStub
	fakeReturns := fake.resolveTypeReturns
	fake.recordInvocation("ResolveType", []interface{}{arg1})
	fake.resolveTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) ResolveTypeCallCount() int {
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	return len(fake.resolveTypeArgsForCall)
}

func (fake *FakeCluster) ResolveTypeCalls(stub func(cluster.TypeRef) (*cluster.Type, error)) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = stub
}

func (fake *FakeCluster) ResolveTypeArgsForCall(i int) cluster.TypeRef {
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	argsForCall := fake.resolveTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) ResolveTypeReturns(result1 *cluster.Type, result2 error) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = nil
	fake.resolveTypeReturns = struct {
		result1 *cluster.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) ResolveTypeReturnsOnCall(i int, result1 *cluster.Type, result2 error) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = nil
	if fake.resolveTypeReturnsOnCall == nil {
		fake.resolveTypeReturnsOnCall = make(map[int]struct {
			result1 *cluster.Type
			result2 error
		})
	}
	fake.resolveTypeReturnsOnCall[i] = struct {
		result1 *cluster.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Sync(arg1 context.Context, arg2 string, arg3 cluster.Syncable) error {
	fake.syncMutex.Lock()
	ret, specificReturn := fake.syncReturnsOnCall[len(fake.syncArgsForCall)]
	fake.syncArgsForCall = append(fake.syncArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 cluster.Syncable
	}{arg1, arg2, arg3})
	stub := fake.SyncStub
	fakeReturns := fake.syncReturns
	fake.recordInvocation("Sync", []interface{}{arg1, arg2, arg3})
	fake.syncMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) SyncCallCount() int {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	return len(fake.syncArgsForCall)
}

func (fake *FakeCluster) SyncCalls(stub func(context.Context, string, cluster.Syncable) error) {
	fake.syncMutex.Lock()
	defer fake.syncMutex.Unlock()
	fake.SyncStub = stub
}

func (fake *FakeCluster) SyncArgsForCall(i int) (context.Context, string, cluster.Syncable) {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	argsForCall := fake.syncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCluster) SyncReturns(result1 error) {
	fake.syncMutex.Lock()
	defer fake.syncMutex.Unlock()
	fake.SyncStub = nil
	fake.syncReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) SyncReturnsOnCall(i int, result1 error) {
	fake.syncMutex.Lock()
	defer fake.syncMutex.Unlock()
	fake.SyncStub = nil
	if fake.syncReturnsOnCall == nil {
		fake.syncReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.syncReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) SyncableVersion(arg1 string, arg2 uint64) (*cluster.Configuration, error) {
	fake.syncableVersionMutex.Lock()
	ret, specificReturn := fake.syncableVersionReturnsOnCall[len(fake.syncableVersionArgsForCall)]
	fake.syncableVersionArgsForCall = append(fake.syncableVersionArgsForCall, struct {
		arg1 string
		arg2 uint64
	}{arg1, arg2})
	stub := fake.SyncableVersionStub
	fakeReturns := fake.syncableVersionReturns
	fake.recordInvocation("SyncableVersion", []interface{}{arg1, arg2})
	fake.syncableVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) SyncableVersionCallCount() int {
	fake.syncableVersionMutex.RLock()
	defer fake.syncableVersionMutex.RUnlock()
	return len(fake.syncableVersionArgsForCall)
}

func (fake *FakeCluster) SyncableVersionCalls(stub func(string, uint64) (*cluster.Configuration, error)) {
	fake.syncableVersionMutex.Lock()
	defer fake.syncableVersionMutex.Unlock()
	fake.SyncableVersionStub = stub
}

func (fake *FakeCluster) SyncableVersionArgsForCall(i int) (string, uint64) {
	fake.syncableVersionMutex.RLock()
	defer fake.syncableVersionMutex.RUnlock()
	argsForCall := fake.syncableVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) SyncableVersionReturns(result1 *cluster.Configuration, result2 error) {
	fake.syncableVersionMutex.Lock()
	defer fake.syncableVersionMutex.Unlock()
	fake.SyncableVersionStub = nil
	fake.syncableVersionReturns = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) SyncableVersionReturnsOnCall(i int, result1 *cluster.Configuration, result2 error) {
	fake.syncableVersionMutex.Lock()
	defer fake.syncableVersionMutex.Unlock()
	fake.SyncableVersionStub = nil
	if fake.syncableVersionReturnsOnCall == nil {
		fake.syncableVersionReturnsOnCall = make(map[int]struct {
			result1 *cluster.Configuration
			result2 error
		})
	}
	fake.syncableVersionReturnsOnCall[i] = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) SyncableVersions(arg1 string) ([]cluster.VersionInfo, error) {
	fake.syncableVersionsMutex.Lock()
	ret, specificReturn := fake.syncableVersionsReturnsOnCall[len(fake.syncableVersionsArgsForCall)]
	fake.syncableVersionsArgsForCall = append(fake.syncableVersionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SyncableVersionsStub
	fakeReturns := fake.syncableVersionsReturns
	fake.recordInvocation("SyncableVersions", []interface{}{arg1})
	fake.syncableVersionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) SyncableVersionsCallCount() int {
	fake.syncableVersionsMutex.RLock()
	defer fake.syncableVersionsMutex.RUnlock()
	return len(fake.syncableVersionsArgsForCall)
}

func (fake *FakeCluster) SyncableVersionsCalls(stub func(string) ([]cluster.VersionInfo, error)) {
	fake.syncableVersionsMutex.Lock()
	defer fake.syncableVersionsMutex.Unlock()
	fake.SyncableVersionsStub = stub
}

func (fake *FakeCluster) SyncableVersionsArgsForCall(i int) string {
	fake.syncableVersionsMutex.RLock()
	defer fake.syncableVersionsMutex.RUnlock()
	argsForCall := fake.syncableVersionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) SyncableVersionsReturns(result1 []cluster.VersionInfo, result2 error) {
	fake.syncableVersionsMutex.Lock()
	defer fake.syncableVersionsMutex.Unlock()
	fake.SyncableVersionsStub = nil
	fake.syncableVersionsReturns = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) SyncableVersionsReturnsOnCall(i int, result1 []cluster.VersionInfo, result2 error) {
	fake.syncableVersionsMutex.Lock()
	defer fake.syncableVersionsMutex.Unlock()
	fake.SyncableVersionsStub = nil
	if fake.syncableVersionsReturnsOnCall == nil {
		fake.syncableVersionsReturnsOnCall = make(map[int]struct {
			result1 []cluster.VersionInfo
			result2 error
		})
	}
	fake.syncableVersionsReturnsOnCall[i] = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Syncables() ([]*cluster.Configuration, error) {
	fake.syncablesMutex.Lock()
	ret, specificReturn := fake.syncablesReturnsOnCall[len(fake.syncablesArgsForCall)]
	fake.syncablesArgsForCall = append(fake.syncablesArgsForCall, struct {
	}{})
	stub := fake.SyncablesStub
	fakeReturns := fake.syncablesReturns
	fake.recordInvocation("Syncables", []interface{}{})
	fake.syncablesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) SyncablesCallCount() int {
	fake.syncablesMutex.RLock()
	defer fake.syncablesMutex.RUnlock()
	return len(fake.syncablesArgsForCall)
}

func (fake *FakeCluster) SyncablesCalls(stub func() ([]*cluster.Configuration, error)) {
	fake.syncablesMutex.Lock()
	defer fake.syncablesMutex.Unlock()
	fake.SyncablesStub = stub
}

func (fake *FakeCluster) SyncablesReturns(result1 []*cluster.Configuration, result2 error) {
	fake.syncablesMutex.Lock()
	defer fake.syncablesMutex.Unlock()
	fake.SyncablesStub = nil
	fake.syncablesReturns = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) SyncablesReturnsOnCall(i int, result1 []*cluster.Configuration, result2 error) {
	fake.syncablesMutex.Lock()
	defer fake.syncablesMutex.Unlock()
	fake.SyncablesStub = nil
	if fake.syncablesReturnsOnCall == nil {
		fake.syncablesReturnsOnCall = make(map[int]struct {
			result1 []*cluster.Configuration
			result2 error
		})
	}
	fake.syncablesReturnsOnCall[i] = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeGraph(arg1 string, arg2 time.Time, arg3 time.Time) ([]cluster.TimePoint, error) {
	fake.typeGraphMutex.Lock()
	ret, specificReturn := fake.typeGraphReturnsOnCall[len(fake.typeGraphArgsForCall)]
	fake.typeGraphArgsForCall = append(fake.typeGraphArgsForCall, struct {
		arg1 string
		arg2 time.Time
		arg3 time.Time
	}{arg1, arg2, arg3})
	stub := fake.TypeGraphStub
	fakeReturns := fake.typeGraphReturns
	fake.recordInvocation("TypeGraph", []interface{}{arg1, arg2, arg3})
	fake.typeGraphMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) TypeGraphCallCount() int {
	fake.typeGraphMutex.RLock()
	defer fake.typeGraphMutex.RUnlock()
	return len(fake.typeGraphArgsForCall)
}

func (fake *FakeCluster) TypeGraphCalls(stub func(string, time.Time, time.Time) ([]cluster.TimePoint, error)) {
	fake.typeGraphMutex.Lock()
	defer fake.typeGraphMutex.Unlock()
	fake.TypeGraphStub = stub
}

func (fake *FakeCluster) TypeGraphArgsForCall(i int) (string, time.Time, time.Time) {
	fake.typeGraphMutex.RLock()
	defer fake.typeGraphMutex.RUnlock()
	argsForCall := fake.typeGraphArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCluster) TypeGraphReturns(result1 []cluster.TimePoint, result2 error) {
	fake.typeGraphMutex.Lock()
	defer fake.typeGraphMutex.Unlock()
	fake.TypeGraphStub = nil
	fake.typeGraphReturns = struct {
		result1 []cluster.TimePoint
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeGraphReturnsOnCall(i int, result1 []cluster.TimePoint, result2 error) {
	fake.typeGraphMutex.Lock()
	defer fake.typeGraphMutex.Unlock()
	fake.TypeGraphStub = nil
	if fake.typeGraphReturnsOnCall == nil {
		fake.typeGraphReturnsOnCall = make(map[int]struct {
			result1 []cluster.TimePoint
			result2 error
		})
	}
	fake.typeGraphReturnsOnCall[i] = struct {
		result1 []cluster.TimePoint
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeVersion(arg1 string, arg2 uint64) (*cluster.Configuration, error) {
	fake.typeVersionMutex.Lock()
	ret, specificReturn := fake.typeVersionReturnsOnCall[len(fake.typeVersionArgsForCall)]
	fake.typeVersionArgsForCall = append(fake.typeVersionArgsForCall, struct {
		arg1 string
		arg2 uint64
	}{arg1, arg2})
	stub := fake.TypeVersionStub
	fakeReturns := fake.typeVersionReturns
	fake.recordInvocation("TypeVersion", []interface{}{arg1, arg2})
	fake.typeVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) TypeVersionCallCount() int {
	fake.typeVersionMutex.RLock()
	defer fake.typeVersionMutex.RUnlock()
	return len(fake.typeVersionArgsForCall)
}

func (fake *FakeCluster) TypeVersionCalls(stub func(string, uint64) (*cluster.Configuration, error)) {
	fake.typeVersionMutex.Lock()
	defer fake.typeVersionMutex.Unlock()
	fake.TypeVersionStub = stub
}

func (fake *FakeCluster) TypeVersionArgsForCall(i int) (string, uint64) {
	fake.typeVersionMutex.RLock()
	defer fake.typeVersionMutex.RUnlock()
	argsForCall := fake.typeVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCluster) TypeVersionReturns(result1 *cluster.Configuration, result2 error) {
	fake.typeVersionMutex.Lock()
	defer fake.typeVersionMutex.Unlock()
	fake.TypeVersionStub = nil
	fake.typeVersionReturns = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeVersionReturnsOnCall(i int, result1 *cluster.Configuration, result2 error) {
	fake.typeVersionMutex.Lock()
	defer fake.typeVersionMutex.Unlock()
	fake.TypeVersionStub = nil
	if fake.typeVersionReturnsOnCall == nil {
		fake.typeVersionReturnsOnCall = make(map[int]struct {
			result1 *cluster.Configuration
			result2 error
		})
	}
	fake.typeVersionReturnsOnCall[i] = struct {
		result1 *cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeVersions(arg1 string) ([]cluster.VersionInfo, error) {
	fake.typeVersionsMutex.Lock()
	ret, specificReturn := fake.typeVersionsReturnsOnCall[len(fake.typeVersionsArgsForCall)]
	fake.typeVersionsArgsForCall = append(fake.typeVersionsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TypeVersionsStub
	fakeReturns := fake.typeVersionsReturns
	fake.recordInvocation("TypeVersions", []interface{}{arg1})
	fake.typeVersionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) TypeVersionsCallCount() int {
	fake.typeVersionsMutex.RLock()
	defer fake.typeVersionsMutex.RUnlock()
	return len(fake.typeVersionsArgsForCall)
}

func (fake *FakeCluster) TypeVersionsCalls(stub func(string) ([]cluster.VersionInfo, error)) {
	fake.typeVersionsMutex.Lock()
	defer fake.typeVersionsMutex.Unlock()
	fake.TypeVersionsStub = stub
}

func (fake *FakeCluster) TypeVersionsArgsForCall(i int) string {
	fake.typeVersionsMutex.RLock()
	defer fake.typeVersionsMutex.RUnlock()
	argsForCall := fake.typeVersionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) TypeVersionsReturns(result1 []cluster.VersionInfo, result2 error) {
	fake.typeVersionsMutex.Lock()
	defer fake.typeVersionsMutex.Unlock()
	fake.TypeVersionsStub = nil
	fake.typeVersionsReturns = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypeVersionsReturnsOnCall(i int, result1 []cluster.VersionInfo, result2 error) {
	fake.typeVersionsMutex.Lock()
	defer fake.typeVersionsMutex.Unlock()
	fake.TypeVersionsStub = nil
	if fake.typeVersionsReturnsOnCall == nil {
		fake.typeVersionsReturnsOnCall = make(map[int]struct {
			result1 []cluster.VersionInfo
			result2 error
		})
	}
	fake.typeVersionsReturnsOnCall[i] = struct {
		result1 []cluster.VersionInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Types() ([]*cluster.Configuration, error) {
	fake.typesMutex.Lock()
	ret, specificReturn := fake.typesReturnsOnCall[len(fake.typesArgsForCall)]
	fake.typesArgsForCall = append(fake.typesArgsForCall, struct {
	}{})
	stub := fake.TypesStub
	fakeReturns := fake.typesReturns
	fake.recordInvocation("Types", []interface{}{})
	fake.typesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) TypesCallCount() int {
	fake.typesMutex.RLock()
	defer fake.typesMutex.RUnlock()
	return len(fake.typesArgsForCall)
}

func (fake *FakeCluster) TypesCalls(stub func() ([]*cluster.Configuration, error)) {
	fake.typesMutex.Lock()
	defer fake.typesMutex.Unlock()
	fake.TypesStub = stub
}

func (fake *FakeCluster) TypesReturns(result1 []*cluster.Configuration, result2 error) {
	fake.typesMutex.Lock()
	defer fake.typesMutex.Unlock()
	fake.TypesStub = nil
	fake.typesReturns = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) TypesReturnsOnCall(i int, result1 []*cluster.Configuration, result2 error) {
	fake.typesMutex.Lock()
	defer fake.typesMutex.Unlock()
	fake.TypesStub = nil
	if fake.typesReturnsOnCall == nil {
		fake.typesReturnsOnCall = make(map[int]struct {
			result1 []*cluster.Configuration
			result2 error
		})
	}
	fake.typesReturnsOnCall[i] = struct {
		result1 []*cluster.Configuration
		result2 error
	}{result1, result2}
}

func (fake *FakeCluster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addDatabaseParserMutex.RLock()
	defer fake.addDatabaseParserMutex.RUnlock()
	fake.addSyncableParserMutex.RLock()
	defer fake.addSyncableParserMutex.RUnlock()
	fake.appliedIndexMutex.RLock()
	defer fake.appliedIndexMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.databaseVersionMutex.RLock()
	defer fake.databaseVersionMutex.RUnlock()
	fake.databaseVersionsMutex.RLock()
	defer fake.databaseVersionsMutex.RUnlock()
	fake.databasesMutex.RLock()
	defer fake.databasesMutex.RUnlock()
	fake.ingestMutex.RLock()
	defer fake.ingestMutex.RUnlock()
	fake.ingestableVersionMutex.RLock()
	defer fake.ingestableVersionMutex.RUnlock()
	fake.ingestableVersionsMutex.RLock()
	defer fake.ingestableVersionsMutex.RUnlock()
	fake.ingestablesMutex.RLock()
	defer fake.ingestablesMutex.RUnlock()
	fake.leaderMutex.RLock()
	defer fake.leaderMutex.RUnlock()
	fake.proposalsMutex.RLock()
	defer fake.proposalsMutex.RUnlock()
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	fake.proposeDatabaseMutex.RLock()
	defer fake.proposeDatabaseMutex.RUnlock()
	fake.proposeDeleteTypeMutex.RLock()
	defer fake.proposeDeleteTypeMutex.RUnlock()
	fake.proposeIngestableMutex.RLock()
	defer fake.proposeIngestableMutex.RUnlock()
	fake.proposeSyncableMutex.RLock()
	defer fake.proposeSyncableMutex.RUnlock()
	fake.proposeTypeMutex.RLock()
	defer fake.proposeTypeMutex.RUnlock()
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	fake.syncableVersionMutex.RLock()
	defer fake.syncableVersionMutex.RUnlock()
	fake.syncableVersionsMutex.RLock()
	defer fake.syncableVersionsMutex.RUnlock()
	fake.syncablesMutex.RLock()
	defer fake.syncablesMutex.RUnlock()
	fake.typeGraphMutex.RLock()
	defer fake.typeGraphMutex.RUnlock()
	fake.typeVersionMutex.RLock()
	defer fake.typeVersionMutex.RUnlock()
	fake.typeVersionsMutex.RLock()
	defer fake.typeVersionsMutex.RUnlock()
	fake.typesMutex.RLock()
	defer fake.typesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCluster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cluster.Cluster = new(FakeCluster)
