// Code generated by counterfeiter. DO NOT EDIT.
package clusterfakes

import (
	"sync"

	"github.com/philborlin/committed/internal/cluster"
	"github.com/spf13/viper"
)

type FakeSyncableParser struct {
	ParseStub        func(*viper.Viper, cluster.DatabaseStorage) (cluster.Syncable, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 *viper.Viper
		arg2 cluster.DatabaseStorage
	}
	parseReturns struct {
		result1 cluster.Syncable
		result2 error
	}
	parseReturnsOnCall map[int]struct {
		result1 cluster.Syncable
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSyncableParser) Parse(arg1 *viper.Viper, arg2 cluster.DatabaseStorage) (cluster.Syncable, error) {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 *viper.Viper
		arg2 cluster.DatabaseStorage
	}{arg1, arg2})
	stub := fake.ParseStub
	fakeReturns := fake.parseReturns
	fake.recordInvocation("Parse", []interface{}{arg1, arg2})
	fake.parseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSyncableParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeSyncableParser) ParseCalls(stub func(*viper.Viper, cluster.DatabaseStorage) (cluster.Syncable, error)) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = stub
}

func (fake *FakeSyncableParser) ParseArgsForCall(i int) (*viper.Viper, cluster.DatabaseStorage) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	argsForCall := fake.parseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSyncableParser) ParseReturns(result1 cluster.Syncable, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 cluster.Syncable
		result2 error
	}{result1, result2}
}

func (fake *FakeSyncableParser) ParseReturnsOnCall(i int, result1 cluster.Syncable, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 cluster.Syncable
			result2 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 cluster.Syncable
		result2 error
	}{result1, result2}
}

func (fake *FakeSyncableParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSyncableParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cluster.SyncableParser = new(FakeSyncableParser)
