// Code generated by counterfeiter. DO NOT EDIT.
package clusterfakes

import (
	"context"
	"sync"

	"github.com/committeddb/committed/internal/cluster"
)

type FakeCluster struct {
	AppliedIndexStub        func() uint64
	appliedIndexMutex       sync.RWMutex
	appliedIndexArgsForCall []struct {
	}
	appliedIndexReturns struct {
		result1 uint64
	}
	appliedIndexReturnsOnCall map[int]struct {
		result1 uint64
	}
	ApplyStalledStub        func() bool
	applyStalledMutex       sync.RWMutex
	applyStalledArgsForCall []struct {
	}
	applyStalledReturns struct {
		result1 bool
	}
	applyStalledReturnsOnCall map[int]struct {
		result1 bool
	}
	IDStub        func() uint64
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 uint64
	}
	iDReturnsOnCall map[int]struct {
		result1 uint64
	}
	LeaderStub        func() uint64
	leaderMutex       sync.RWMutex
	leaderArgsForCall []struct {
	}
	leaderReturns struct {
		result1 uint64
	}
	leaderReturnsOnCall map[int]struct {
		result1 uint64
	}
	LinearizableReadStub        func(context.Context) error
	linearizableReadMutex       sync.RWMutex
	linearizableReadArgsForCall []struct {
		arg1 context.Context
	}
	linearizableReadReturns struct {
		result1 error
	}
	linearizableReadReturnsOnCall map[int]struct {
		result1 error
	}
	MemberAPIURLStub        func(uint64) (string, bool)
	memberAPIURLMutex       sync.RWMutex
	memberAPIURLArgsForCall []struct {
		arg1 uint64
	}
	memberAPIURLReturns struct {
		result1 string
		result2 bool
	}
	memberAPIURLReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCluster) AppliedIndex() uint64 {
	fake.appliedIndexMutex.Lock()
	ret, specificReturn := fake.appliedIndexReturnsOnCall[len(fake.appliedIndexArgsForCall)]
	fake.appliedIndexArgsForCall = append(fake.appliedIndexArgsForCall, struct {
	}{})
	stub := fake.AppliedIndexStub
	fakeReturns := fake.appliedIndexReturns
	fake.recordInvocation("AppliedIndex", []interface{}{})
	fake.appliedIndexMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) AppliedIndexCallCount() int {
	fake.appliedIndexMutex.RLock()
	defer fake.appliedIndexMutex.RUnlock()
	return len(fake.appliedIndexArgsForCall)
}

func (fake *FakeCluster) AppliedIndexCalls(stub func() uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = stub
}

func (fake *FakeCluster) AppliedIndexReturns(result1 uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = nil
	fake.appliedIndexReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) AppliedIndexReturnsOnCall(i int, result1 uint64) {
	fake.appliedIndexMutex.Lock()
	defer fake.appliedIndexMutex.Unlock()
	fake.AppliedIndexStub = nil
	if fake.appliedIndexReturnsOnCall == nil {
		fake.appliedIndexReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.appliedIndexReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) ApplyStalled() bool {
	fake.applyStalledMutex.Lock()
	ret, specificReturn := fake.applyStalledReturnsOnCall[len(fake.applyStalledArgsForCall)]
	fake.applyStalledArgsForCall = append(fake.applyStalledArgsForCall, struct {
	}{})
	stub := fake.ApplyStalledStub
	fakeReturns := fake.applyStalledReturns
	fake.recordInvocation("ApplyStalled", []interface{}{})
	fake.applyStalledMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) ApplyStalledCallCount() int {
	fake.applyStalledMutex.RLock()
	defer fake.applyStalledMutex.RUnlock()
	return len(fake.applyStalledArgsForCall)
}

func (fake *FakeCluster) ApplyStalledCalls(stub func() bool) {
	fake.applyStalledMutex.Lock()
	defer fake.applyStalledMutex.Unlock()
	fake.ApplyStalledStub = stub
}

func (fake *FakeCluster) ApplyStalledReturns(result1 bool) {
	fake.applyStalledMutex.Lock()
	defer fake.applyStalledMutex.Unlock()
	fake.ApplyStalledStub = nil
	fake.applyStalledReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCluster) ApplyStalledReturnsOnCall(i int, result1 bool) {
	fake.applyStalledMutex.Lock()
	defer fake.applyStalledMutex.Unlock()
	fake.ApplyStalledStub = nil
	if fake.applyStalledReturnsOnCall == nil {
		fake.applyStalledReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.applyStalledReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeCluster) ID() uint64 {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakeCluster) IDCalls(stub func() uint64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *FakeCluster) IDReturns(result1 uint64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) IDReturnsOnCall(i int, result1 uint64) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) Leader() uint64 {
	fake.leaderMutex.Lock()
	ret, specificReturn := fake.leaderReturnsOnCall[len(fake.leaderArgsForCall)]
	fake.leaderArgsForCall = append(fake.leaderArgsForCall, struct {
	}{})
	stub := fake.LeaderStub
	fakeReturns := fake.leaderReturns
	fake.recordInvocation("Leader", []interface{}{})
	fake.leaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) LeaderCallCount() int {
	fake.leaderMutex.RLock()
	defer fake.leaderMutex.RUnlock()
	return len(fake.leaderArgsForCall)
}

func (fake *FakeCluster) LeaderCalls(stub func() uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = stub
}

func (fake *FakeCluster) LeaderReturns(result1 uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	fake.leaderReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) LeaderReturnsOnCall(i int, result1 uint64) {
	fake.leaderMutex.Lock()
	defer fake.leaderMutex.Unlock()
	fake.LeaderStub = nil
	if fake.leaderReturnsOnCall == nil {
		fake.leaderReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.leaderReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeCluster) LinearizableRead(arg1 context.Context) error {
	fake.linearizableReadMutex.Lock()
	ret, specificReturn := fake.linearizableReadReturnsOnCall[len(fake.linearizableReadArgsForCall)]
	fake.linearizableReadArgsForCall = append(fake.linearizableReadArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.LinearizableReadStub
	fakeReturns := fake.linearizableReadReturns
	fake.recordInvocation("LinearizableRead", []interface{}{arg1})
	fake.linearizableReadMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCluster) LinearizableReadCallCount() int {
	fake.linearizableReadMutex.RLock()
	defer fake.linearizableReadMutex.RUnlock()
	return len(fake.linearizableReadArgsForCall)
}

func (fake *FakeCluster) LinearizableReadCalls(stub func(context.Context) error) {
	fake.linearizableReadMutex.Lock()
	defer fake.linearizableReadMutex.Unlock()
	fake.LinearizableReadStub = stub
}

func (fake *FakeCluster) LinearizableReadArgsForCall(i int) context.Context {
	fake.linearizableReadMutex.RLock()
	defer fake.linearizableReadMutex.RUnlock()
	argsForCall := fake.linearizableReadArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) LinearizableReadReturns(result1 error) {
	fake.linearizableReadMutex.Lock()
	defer fake.linearizableReadMutex.Unlock()
	fake.LinearizableReadStub = nil
	fake.linearizableReadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) LinearizableReadReturnsOnCall(i int, result1 error) {
	fake.linearizableReadMutex.Lock()
	defer fake.linearizableReadMutex.Unlock()
	fake.LinearizableReadStub = nil
	if fake.linearizableReadReturnsOnCall == nil {
		fake.linearizableReadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.linearizableReadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCluster) MemberAPIURL(arg1 uint64) (string, bool) {
	fake.memberAPIURLMutex.Lock()
	ret, specificReturn := fake.memberAPIURLReturnsOnCall[len(fake.memberAPIURLArgsForCall)]
	fake.memberAPIURLArgsForCall = append(fake.memberAPIURLArgsForCall, struct {
		arg1 uint64
	}{arg1})
	stub := fake.MemberAPIURLStub
	fakeReturns := fake.memberAPIURLReturns
	fake.recordInvocation("MemberAPIURL", []interface{}{arg1})
	fake.memberAPIURLMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCluster) MemberAPIURLCallCount() int {
	fake.memberAPIURLMutex.RLock()
	defer fake.memberAPIURLMutex.RUnlock()
	return len(fake.memberAPIURLArgsForCall)
}

func (fake *FakeCluster) MemberAPIURLCalls(stub func(uint64) (string, bool)) {
	fake.memberAPIURLMutex.Lock()
	defer fake.memberAPIURLMutex.Unlock()
	fake.MemberAPIURLStub = stub
}

func (fake *FakeCluster) MemberAPIURLArgsForCall(i int) uint64 {
	fake.memberAPIURLMutex.RLock()
	defer fake.memberAPIURLMutex.RUnlock()
	argsForCall := fake.memberAPIURLArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCluster) MemberAPIURLReturns(result1 string, result2 bool) {
	fake.memberAPIURLMutex.Lock()
	defer fake.memberAPIURLMutex.Unlock()
	fake.MemberAPIURLStub = nil
	fake.memberAPIURLReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeCluster) MemberAPIURLReturnsOnCall(i int, result1 string, result2 bool) {
	fake.memberAPIURLMutex.Lock()
	defer fake.memberAPIURLMutex.Unlock()
	fake.MemberAPIURLStub = nil
	if fake.memberAPIURLReturnsOnCall == nil {
		fake.memberAPIURLReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.memberAPIURLReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeCluster) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCluster) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cluster.Cluster = new(FakeCluster)
