// Code generated by counterfeiter. DO NOT EDIT.
package sqlfakes

import (
	"sync"

	"github.com/philborlin/committed/internal/cluster"
	"github.com/philborlin/committed/internal/cluster/ingestable/sql"
)

type FakeTyper struct {
	ResolveTypeStub        func(cluster.TypeRef) (*cluster.Type, error)
	resolveTypeMutex       sync.RWMutex
	resolveTypeArgsForCall []struct {
		arg1 cluster.TypeRef
	}
	resolveTypeReturns struct {
		result1 *cluster.Type
		result2 error
	}
	resolveTypeReturnsOnCall map[int]struct {
		result1 *cluster.Type
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTyper) ResolveType(arg1 cluster.TypeRef) (*cluster.Type, error) {
	fake.resolveTypeMutex.Lock()
	ret, specificReturn := fake.resolveTypeReturnsOnCall[len(fake.resolveTypeArgsForCall)]
	fake.resolveTypeArgsForCall = append(fake.resolveTypeArgsForCall, struct {
		arg1 cluster.TypeRef
	}{arg1})
	stub := fake.ResolveTypeStub
	fakeReturns := fake.resolveTypeReturns
	fake.recordInvocation("ResolveType", []interface{}{arg1})
	fake.resolveTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTyper) ResolveTypeCallCount() int {
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	return len(fake.resolveTypeArgsForCall)
}

func (fake *FakeTyper) ResolveTypeCalls(stub func(cluster.TypeRef) (*cluster.Type, error)) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = stub
}

func (fake *FakeTyper) ResolveTypeArgsForCall(i int) cluster.TypeRef {
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	argsForCall := fake.resolveTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTyper) ResolveTypeReturns(result1 *cluster.Type, result2 error) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = nil
	fake.resolveTypeReturns = struct {
		result1 *cluster.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeTyper) ResolveTypeReturnsOnCall(i int, result1 *cluster.Type, result2 error) {
	fake.resolveTypeMutex.Lock()
	defer fake.resolveTypeMutex.Unlock()
	fake.ResolveTypeStub = nil
	if fake.resolveTypeReturnsOnCall == nil {
		fake.resolveTypeReturnsOnCall = make(map[int]struct {
			result1 *cluster.Type
			result2 error
		})
	}
	fake.resolveTypeReturnsOnCall[i] = struct {
		result1 *cluster.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeTyper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.resolveTypeMutex.RLock()
	defer fake.resolveTypeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTyper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sql.Typer = new(FakeTyper)
