// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"sync"

	"github.com/philborlin/committed/types"
)

type FakeProposer struct {
	ProposeStub        func(types.Proposal)
	proposeMutex       sync.RWMutex
	proposeArgsForCall []struct {
		arg1 types.Proposal
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProposer) Propose(arg1 types.Proposal) {
	fake.proposeMutex.Lock()
	fake.proposeArgsForCall = append(fake.proposeArgsForCall, struct {
		arg1 types.Proposal
	}{arg1})
	fake.recordInvocation("Propose", []interface{}{arg1})
	fake.proposeMutex.Unlock()
	if fake.ProposeStub != nil {
		fake.ProposeStub(arg1)
	}
}

func (fake *FakeProposer) ProposeCallCount() int {
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	return len(fake.proposeArgsForCall)
}

func (fake *FakeProposer) ProposeCalls(stub func(types.Proposal)) {
	fake.proposeMutex.Lock()
	defer fake.proposeMutex.Unlock()
	fake.ProposeStub = stub
}

func (fake *FakeProposer) ProposeArgsForCall(i int) types.Proposal {
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	argsForCall := fake.proposeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProposer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.proposeMutex.RLock()
	defer fake.proposeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProposer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.Proposer = new(FakeProposer)
