[syncable]
name="two"
type="sql"

[sql]
topic = "simple"
db = "foo"
table = "two"
primaryKey = "pk"

[[sql.indexes]]
name = "firstIndex"
index = "body"

[[sql.mappings]]
jsonPath = "$.id"
column = "pk"
type = "VARCHAR(256)"

[[sql.mappings]]
jsonPath = "$.body"
column = "body"
type = "VARCHAR(256)"