[syncable]
name="one"
type="sql"

[sql]
topic = "simple"
db = "foo"
table = "one"
primaryKey = "pk"

[[sql.indexes]]
name = "firstIndex"
index = "title"

[[sql.mappings]]
jsonPath = "$.key"
column = "pk"
type = "VARCHAR(256)"

[[sql.mappings]]
jsonPath = "$.one"
column = "title"
type = "VARCHAR(256)"