/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DatabasesImport } from './routes/databases'

// Create Virtual Routes

const SyncablesLazyImport = createFileRoute('/syncables')()
const IngestablesLazyImport = createFileRoute('/ingestables')()
const IndexLazyImport = createFileRoute('/')()
const DatabasesDatabaseIdLazyImport = createFileRoute(
  '/databases/$databaseId',
)()

// Create/Update Routes

const SyncablesLazyRoute = SyncablesLazyImport.update({
  id: '/syncables',
  path: '/syncables',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/syncables.lazy').then((d) => d.Route))

const IngestablesLazyRoute = IngestablesLazyImport.update({
  id: '/ingestables',
  path: '/ingestables',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ingestables.lazy').then((d) => d.Route))

const DatabasesRoute = DatabasesImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DatabasesDatabaseIdLazyRoute = DatabasesDatabaseIdLazyImport.update({
  id: '/$databaseId',
  path: '/$databaseId',
  getParentRoute: () => DatabasesRoute,
} as any).lazy(() =>
  import('./routes/databases.$databaseId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesImport
      parentRoute: typeof rootRoute
    }
    '/ingestables': {
      id: '/ingestables'
      path: '/ingestables'
      fullPath: '/ingestables'
      preLoaderRoute: typeof IngestablesLazyImport
      parentRoute: typeof rootRoute
    }
    '/syncables': {
      id: '/syncables'
      path: '/syncables'
      fullPath: '/syncables'
      preLoaderRoute: typeof SyncablesLazyImport
      parentRoute: typeof rootRoute
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdLazyImport
      parentRoute: typeof DatabasesImport
    }
  }
}

// Create and export the route tree

interface DatabasesRouteChildren {
  DatabasesDatabaseIdLazyRoute: typeof DatabasesDatabaseIdLazyRoute
}

const DatabasesRouteChildren: DatabasesRouteChildren = {
  DatabasesDatabaseIdLazyRoute: DatabasesDatabaseIdLazyRoute,
}

const DatabasesRouteWithChildren = DatabasesRoute._addFileChildren(
  DatabasesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/ingestables': typeof IngestablesLazyRoute
  '/syncables': typeof SyncablesLazyRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/ingestables': typeof IngestablesLazyRoute
  '/syncables': typeof SyncablesLazyRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/ingestables': typeof IngestablesLazyRoute
  '/syncables': typeof SyncablesLazyRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/databases'
    | '/ingestables'
    | '/syncables'
    | '/databases/$databaseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/databases'
    | '/ingestables'
    | '/syncables'
    | '/databases/$databaseId'
  id:
    | '__root__'
    | '/'
    | '/databases'
    | '/ingestables'
    | '/syncables'
    | '/databases/$databaseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DatabasesRoute: typeof DatabasesRouteWithChildren
  IngestablesLazyRoute: typeof IngestablesLazyRoute
  SyncablesLazyRoute: typeof SyncablesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DatabasesRoute: DatabasesRouteWithChildren,
  IngestablesLazyRoute: IngestablesLazyRoute,
  SyncablesLazyRoute: SyncablesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/databases",
        "/ingestables",
        "/syncables"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/databases": {
      "filePath": "databases.tsx",
      "children": [
        "/databases/$databaseId"
      ]
    },
    "/ingestables": {
      "filePath": "ingestables.lazy.tsx"
    },
    "/syncables": {
      "filePath": "syncables.lazy.tsx"
    },
    "/databases/$databaseId": {
      "filePath": "databases.$databaseId.lazy.tsx",
      "parent": "/databases"
    }
  }
}
ROUTE_MANIFEST_END */
